// ── DOM refs ───────────────────────────────────────────────────────────────

export const dom = {
  app: document.getElementById('app'),
  welcome: document.getElementById('welcome'),
  main: document.getElementById('main'),
  photoGrid: document.getElementById('photo-grid'),
  gridPanel: document.getElementById('grid-panel'),
  detailEmpty: document.getElementById('detail-empty'),
  exportControls: document.getElementById('export-controls'),
  gifPreviewWrap: document.getElementById('gif-preview-wrap'),
  gifPreviewCanvas: document.getElementById('gif-preview-canvas'),
  gifPreviewInfo: document.getElementById('gif-preview-info'),
  soloView: document.getElementById('solo-view'),
  soloCanvas: document.getElementById('solo-canvas'),
  soloLabel: document.getElementById('solo-label'),
  soloMeta: document.getElementById('solo-meta'),
  gifToolbar: document.getElementById('gif-toolbar'),
  gifFrameStrip: document.getElementById('gif-frame-strip'),
  gifFrameList: document.getElementById('gif-frame-list'),
  gifFrameEmpty: document.getElementById('gif-frame-empty'),
  gifCount: document.getElementById('gif-count'),
  gifDelay: document.getElementById('gif-delay'),
  gifDelayVal: document.getElementById('gif-delay-val'),
  statusText: document.getElementById('status-text'),
  statusDot: document.getElementById('status-dot'),
  pocketModal: document.getElementById('pocket-modal'),
  pocketSaveList: document.getElementById('pocket-save-list'),
  pocketConfirm: document.getElementById('pocket-confirm'),
  toast: document.getElementById('toast'),
  dropOverlay: document.getElementById('drop-overlay'),
  presentationOverlay: document.getElementById('presentation-overlay'),
  presCanvas: document.getElementById('pres-canvas'),
  presLabel: document.getElementById('pres-label'),
  presClose: document.getElementById('pres-close'),
  presPrev: document.getElementById('pres-prev'),
  presNext: document.getElementById('pres-next'),
};
