/**
 * palettes-ext.js — Extended palette library for DMG DarkRoom
 *
 * Sources / Credits:
 *   • TheWolfBunny64       https://github.com/TheWolfBunny64
 *   • R.A.Helllord         Analogue Pocket palette collection
 *   • Trashuncle           Analogue Pocket palette collection
 *   • GBC game palettes    Nintendo GBC bootstrap ROM (sourced from TCRF)
 *   • SGB palettes         Super Game Boy (sourced from TCRF)
 *   • Community Gallery    GalleryWebApp / lospec.com contributors
 *   • BGB / SameBoy        Emulator default palettes
 *
 *   Collection assembled by the r/AnaloguePocket community:
 *   https://www.reddit.com/r/AnaloguePocket/comments/18q2iz1/
 *
 * Loaded after palettes.js — merges into window.PALETTES.
 */

(function () {
  'use strict';
  const ext = {

    // ── GBC Game Palettes ─────────────────────────────────────
    gbc_game_alleyway_world: { id: 'gbc_game_alleyway_world', name: "Alleyway (World)", group: 'gbc_game', colors: ['#ffff00', '#a59cff', '#006300', '#000000'] },
    gbc_game_arcade_classic_no_1_asteroids_missile_command_usa_europe: { id: 'gbc_game_arcade_classic_no_1_asteroids_missile_command_usa_europe', name: "Arcade Classic No. 1 - Asteroids _ Missile Command (USA, Europe)", group: 'gbc_game', colors: ['#ffffff', '#7bff31', '#008400', '#000000'] },
    gbc_game_balloon_kid_usa_europe: { id: 'gbc_game_balloon_kid_usa_europe', name: "Balloon Kid (USA, Europe)", group: 'gbc_game', colors: ['#ffffff', '#ff9c00', '#ff0000', '#000000'] },
    gbc_game_baseball_world: { id: 'gbc_game_baseball_world', name: "Baseball (World)", group: 'gbc_game', colors: ['#ffffff', '#ffff00', '#52de00', '#ff8400'] },
    gbc_game_donkey_kong_land_usa_europe: { id: 'gbc_game_donkey_kong_land_usa_europe', name: "Donkey Kong Land (USA, Europe)", group: 'gbc_game', colors: ['#ffff9c', '#94b5ff', '#639473', '#003a3a'] },
    gbc_game_game_boy_gallery_japan: { id: 'gbc_game_game_boy_gallery_japan', name: "Game Boy Gallery (Japan)", group: 'gbc_game', colors: ['#ffffff', '#7bff00', '#b57300', '#000000'] },
    gbc_game_game_boy_wars_japan: { id: 'gbc_game_game_boy_wars_japan', name: "Game Boy Wars (Japan)", group: 'gbc_game', colors: ['#ffffff', '#adad84', '#42737b', '#000000'] },
    gbc_game_soccer_europe_en_fr_de: { id: 'gbc_game_soccer_europe_en_fr_de', name: "Soccer (Europe) (En,Fr,De)", group: 'gbc_game', colors: ['#ffffff', '#6bff00', '#ff524a', '#000000'] },
    gbc_game_super_mario_land_world_rev_a: { id: 'gbc_game_super_mario_land_world_rev_a', name: "Super Mario Land (World) (Rev A)", group: 'gbc_game', colors: ['#ffff94', '#b5b5ff', '#ad5a42', '#000000'] },
    gbc_game_super_mario_land_2_6_golden_coins_usa_europe_rev_a: { id: 'gbc_game_super_mario_land_2_6_golden_coins_usa_europe_rev_a', name: "Super Mario Land 2 - 6 Golden Coins (USA, Europe) (Rev A)", group: 'gbc_game', colors: ['#ffffce', '#63efef', '#9c8431', '#5a5a5a'] },

    // ── Community Gallery ─────────────────────────────────────
    gallery_artistic_caffeinated_lactose: { id: 'gallery_artistic_caffeinated_lactose', name: "Artistic Caffeinated Lactose", group: 'gallery', colors: ['#fdfef5', '#dea963', '#9e754f', '#241606'] },
    gallery_audi_quattro_pikes_peak: { id: 'gallery_audi_quattro_pikes_peak', name: "Audi Quattro Pikes Peak", group: 'gallery', colors: ['#ebeee7', '#868779', '#fa2b25', '#2a201e'] },
    gallery_azure_clouds: { id: 'gallery_azure_clouds', name: "Azure Clouds", group: 'gallery', colors: ['#47ff99', '#32b66d', '#124127', '#000000'] },
    gallery_bgb_emulator: { id: 'gallery_bgb_emulator', name: "BGB Emulator", group: 'gallery', colors: ['#e0f8d0', '#88c070', '#346856', '#081820'] },
    gallery_black_zero: { id: 'gallery_black_zero', name: "Black Zero", group: 'gallery', colors: ['#7e8416', '#577b46', '#385d49', '#2e463d'] },
    gallery_cga_palette_crush_1: { id: 'gallery_cga_palette_crush_1', name: "CGA Palette Crush 1", group: 'gallery', colors: ['#ffffff', '#55ffff', '#ff55ff', '#000000'] },
    gallery_cga_palette_crush_2: { id: 'gallery_cga_palette_crush_2', name: "CGA Palette Crush 2", group: 'gallery', colors: ['#ffffff', '#55ffff', '#ff5555', '#000000'] },
    gallery_cmykeystone: { id: 'gallery_cmykeystone', name: "CMYKeystone", group: 'gallery', colors: ['#ffff00', '#0be8fd', '#fb00fa', '#373737'] },
    gallery_candy_cotton_tower_raid: { id: 'gallery_candy_cotton_tower_raid', name: "Candy Cotton Tower Raid", group: 'gallery', colors: ['#e6aec4', '#e65790', '#8f0039', '#380016'] },
    gallery_caramel_fudge_paranoia: { id: 'gallery_caramel_fudge_paranoia', name: "Caramel Fudge Paranoia", group: 'gallery', colors: ['#cf9255', '#cf7163', '#b01553', '#3f1711'] },
    gallery_cyanide_blues: { id: 'gallery_cyanide_blues', name: "Cyanide Blues", group: 'gallery', colors: ['#9efbe3', '#21aff5', '#1e4793', '#0e1e3d'] },
    gallery_deep_haze_green: { id: 'gallery_deep_haze_green', name: "Deep Haze Green", group: 'gallery', colors: ['#a1d909', '#467818', '#27421f', '#000000'] },
    gallery_dies_ist_meine_wassermelone: { id: 'gallery_dies_ist_meine_wassermelone', name: "Dies ist meine Wassermelone", group: 'gallery', colors: ['#ffdbcb', '#f27d7a', '#558429', '#222903'] },
    gallery_drowning_at_night: { id: 'gallery_drowning_at_night', name: "Drowning at Night", group: 'gallery', colors: ['#a9b0b3', '#586164', '#20293f', '#030c22'] },
    gallery_dune_2000_remastered: { id: 'gallery_dune_2000_remastered', name: "Dune 2000 Remastered", group: 'gallery', colors: ['#fbf1cd', '#c09e7d', '#725441', '#000000'] },
    gallery_flowerfeldstrasse: { id: 'gallery_flowerfeldstrasse', name: "Flowerfeldstrasse", group: 'gallery', colors: ['#e9d9cc', '#c5c5ce', '#75868f', '#171f62'] },
    gallery_floyd_steinberg_in_love: { id: 'gallery_floyd_steinberg_in_love', name: "Floyd Steinberg in Love", group: 'gallery', colors: ['#eaf5fa', '#5fb1f5', '#d23c4e', '#4c1c2d'] },
    gallery_game_boy_light: { id: 'gallery_game_boy_light', name: "Game Boy Light", group: 'gallery', colors: ['#1ddece', '#19c7b3', '#16a596', '#0b7a6d'] },
    gallery_glowing_mountains: { id: 'gallery_glowing_mountains', name: "Glowing Mountains", group: 'gallery', colors: ['#ffbf98', '#a1a8b8', '#514f6c', '#2f1c35'] },
    gallery_golden_elephant_curry: { id: 'gallery_golden_elephant_curry', name: "Golden Elephant Curry", group: 'gallery', colors: ['#ff9c00', '#c27600', '#4f3000', '#000000'] },
    gallery_grafixkid_gray: { id: 'gallery_grafixkid_gray', name: "Grafixkid Gray", group: 'gallery', colors: ['#e0dbcd', '#a89f94', '#706b66', '#2b2b26'] },
    gallery_grafixkid_green: { id: 'gallery_grafixkid_green', name: "Grafixkid Green", group: 'gallery', colors: ['#dbf4b4', '#abc396', '#7b9278', '#4c625a'] },
    gallery_knee_deep_in_the_wood: { id: 'gallery_knee_deep_in_the_wood', name: "Knee-Deep in the Wood", group: 'gallery', colors: ['#fffe6e', '#d5690f', '#3c3ca9', '#2c2410'] },
    gallery_metroid_aran_remixed: { id: 'gallery_metroid_aran_remixed', name: "Metroid Aran Remixed", group: 'gallery', colors: ['#aedf1e', '#b62558', '#047e60', '#2c1700'] },
    gallery_my_friend_from_bavaria: { id: 'gallery_my_friend_from_bavaria', name: "My Friend from Bavaria", group: 'gallery', colors: ['#feda1b', '#df7925', '#b60077', '#382977'] },
    gallery_nortorious_comadante: { id: 'gallery_nortorious_comadante', name: "Nortorious Comadante", group: 'gallery', colors: ['#fcfe54', '#54fefc', '#04aaac', '#0402ac'] },
    gallery_original_game_boy: { id: 'gallery_original_game_boy', name: "Original Game Boy", group: 'gallery', colors: ['#9bbc0f', '#77a112', '#306230', '#0f380f'] },
    gallery_purple_rain: { id: 'gallery_purple_rain', name: "Purple Rain", group: 'gallery', colors: ['#adfffc', '#8570b2', '#ff0084', '#68006a'] },
    gallery_romeros_garden: { id: 'gallery_romeros_garden', name: "Romeros Garden", group: 'gallery', colors: ['#ebc4ab', '#649a57', '#574431', '#323727'] },
    gallery_starlit_memories: { id: 'gallery_starlit_memories', name: "Starlit Memories", group: 'gallery', colors: ['#869ad9', '#6d53bd', '#6f2096', '#4f133f'] },
    gallery_sunflower_holidays: { id: 'gallery_sunflower_holidays', name: "Sunflower Holidays", group: 'gallery', colors: ['#ffff55', '#ff5555', '#881400', '#000000'] },
    gallery_super_hyper_mega_gameboy: { id: 'gallery_super_hyper_mega_gameboy', name: "Super Hyper Mega Gameboy", group: 'gallery', colors: ['#f7e7c6', '#d68e49', '#a63725', '#331e50'] },
    gallery_the_death_of_yung_columbus: { id: 'gallery_the_death_of_yung_columbus', name: "The death of Yung Columbus", group: 'gallery', colors: ['#b5ff32', '#ff2261', '#462917', '#1d1414'] },
    gallery_the_starry_knight: { id: 'gallery_the_starry_knight', name: "The starry knight", group: 'gallery', colors: ['#f5db37', '#37cae5', '#0f86b6', '#123f77'] },
    gallery_there_is_always_money: { id: 'gallery_there_is_always_money', name: "There is Always Money", group: 'gallery', colors: ['#fdfe0a', '#fed638', '#977b25', '#221a09'] },
    gallery_tramonto_al_parco_degli_acquedotti: { id: 'gallery_tramonto_al_parco_degli_acquedotti', name: "Tramonto al Parco degli Acquedotti", group: 'gallery', colors: ['#f3c677', '#e64a4e', '#912978', '#0c0a3e'] },
    gallery_virtual_boy_1985: { id: 'gallery_virtual_boy_1985', name: "Virtual Boy 1985", group: 'gallery', colors: ['#ff0000', '#db0000', '#520000', '#000000'] },
    gallery_waterfront_plaza: { id: 'gallery_waterfront_plaza', name: "Waterfront Plaza", group: 'gallery', colors: ['#cecece', '#6f9edf', '#42678e', '#102533'] },
    gallery_youth_ikarus_reloaded: { id: 'gallery_youth_ikarus_reloaded', name: "Youth Ikarus reloaded", group: 'gallery', colors: ['#cef7f7', '#f78e50', '#9e0000', '#1e0000'] },

    // ── Super Game Boy ────────────────────────────────────────
    sgb_1_a_default_balloon_kid: { id: 'sgb_1_a_default_balloon_kid', name: "1-A (Default) (Balloon Kid)", group: 'sgb', colors: ['#ffefce', '#de944a', '#ad2921', '#311852'] },
    sgb_1_b_wario_land: { id: 'sgb_1_b_wario_land', name: "1-B (Wario Land)", group: 'sgb', colors: ['#dedec6', '#ceb573', '#b55210', '#000000'] },
    sgb_1_c_kirby_s_pinball_land: { id: 'sgb_1_c_kirby_s_pinball_land', name: "1-C (Kirby's Pinball Land)", group: 'sgb', colors: ['#ffc6ff', '#ef9c52', '#9c3963', '#39399c'] },
    sgb_1_d_yoshi_s_cookie_yoshi_no_cooki: { id: 'sgb_1_d_yoshi_s_cookie_yoshi_no_cooki', name: "1-D (Yoshi's Cookie) (Yoshi no Cooki)", group: 'sgb', colors: ['#ffffad', '#c6844a', '#ff0000', '#521800'] },
    sgb_1_e_zelda_link_s_awakening: { id: 'sgb_1_e_zelda_link_s_awakening', name: "1-E (Zelda Link's Awakening)", group: 'sgb', colors: ['#ffdeb5', '#7bc67b', '#6b8c42', '#5a3921'] },
    sgb_1_f_super_mario_land: { id: 'sgb_1_f_super_mario_land', name: "1-F (Super Mario Land)", group: 'sgb', colors: ['#deefff', '#e78c52', '#ad0000', '#004210'] },
    sgb_1_g_solar_striker: { id: 'sgb_1_g_solar_striker', name: "1-G (Solar Striker)", group: 'sgb', colors: ['#ffff5a', '#00a5ef', '#7b7b00', '#000052'] },
    sgb_1_h: { id: 'sgb_1_h', name: "1-H", group: 'sgb', colors: ['#ffefe7', '#ffbd8c', '#844200', '#311800'] },
    sgb_2_a_kaeru_no_tamei: { id: 'sgb_2_a_kaeru_no_tamei', name: "2-A (Kaeru no Tamei)", group: 'sgb', colors: ['#f7cea5', '#c68c4a', '#297b00', '#000000'] },
    sgb_2_b: { id: 'sgb_2_b', name: "2-B", group: 'sgb', colors: ['#ffffff', '#ffef52', '#ff3100', '#52005a'] },
    sgb_2_c_kirby_s_dreal_land_hoshino_kirbi_bi: { id: 'sgb_2_c_kirby_s_dreal_land_hoshino_kirbi_bi', name: "2-C (Kirby's Dreal Land) (Hoshino Kirbi Bi)", group: 'sgb', colors: ['#ffc6ff', '#ef8c8c', '#7b31ef', '#29299c'] },
    sgb_2_d_yoshi_mario_yoshi_yoshi_no_tamago: { id: 'sgb_2_d_yoshi_mario_yoshi_yoshi_no_tamago', name: "2-D (Yoshi, Mario & Yoshi) (Yoshi no Tamago)", group: 'sgb', colors: ['#ffffa5', '#00ff00', '#ff3100', '#000052'] },
    sgb_2_e: { id: 'sgb_2_e', name: "2-E", group: 'sgb', colors: ['#ffce84', '#94b5e7', '#291063', '#100810'] },
    sgb_2_f_kid_icarus_of_myths_and_monsters: { id: 'sgb_2_f_kid_icarus_of_myths_and_monsters', name: "2-F (Kid Icarus of Myths and Monsters)", group: 'sgb', colors: ['#d6ffff', '#ff9452', '#a50000', '#180000'] },
    sgb_2_g_baseball: { id: 'sgb_2_g_baseball', name: "2-G (Baseball)", group: 'sgb', colors: ['#e7bd84', '#6bbd39', '#e75242', '#001800'] },
    sgb_2_h: { id: 'sgb_2_h', name: "2-H", group: 'sgb', colors: ['#ffffff', '#bdbdbd', '#737373', '#000000'] },
    sgb_3_a_tetris: { id: 'sgb_3_a_tetris', name: "3-A (Tetris)", group: 'sgb', colors: ['#ffd69c', '#73c6c6', '#ff6329', '#314a63'] },
    sgb_3_b_dr_mario: { id: 'sgb_3_b_dr_mario', name: "3-B (Dr. Mario)", group: 'sgb', colors: ['#dedec6', '#e78421', '#005200', '#001010'] },
    sgb_3_c_yakyuuman: { id: 'sgb_3_c_yakyuuman', name: "3-C (Yakyuuman)", group: 'sgb', colors: ['#ffff7b', '#e7adce', '#00bdff', '#21215a'] },
    sgb_3_d_super_mario_land_2: { id: 'sgb_3_d_super_mario_land_2', name: "3-D (Super Mario Land 2)", group: 'sgb', colors: ['#f7ffbd', '#e7ad7b', '#08ce00', '#000000'] },
    sgb_3_e_game_boy_wars: { id: 'sgb_3_e_game_boy_wars', name: "3-E (Game Boy Wars)", group: 'sgb', colors: ['#ffffc6', '#e7b56b', '#b57b21', '#524a73'] },
    sgb_3_f_alleyway: { id: 'sgb_3_f_alleyway', name: "3-F (Alleyway)", group: 'sgb', colors: ['#ffd600', '#ff6bff', '#7b7bce', '#424242'] },
    sgb_3_g_tennis: { id: 'sgb_3_g_tennis', name: "3-G (Tennis)", group: 'sgb', colors: ['#ffffff', '#63de52', '#ce3139', '#390000'] },
    sgb_3_h_golf: { id: 'sgb_3_h_golf', name: "3-H (Golf)", group: 'sgb', colors: ['#e7ffa5', '#7bce39', '#4a8c18', '#081800'] },
    sgb_4_a_qix: { id: 'sgb_4_a_qix', name: "4-A (Qix)", group: 'sgb', colors: ['#f7ad6b', '#7badff', '#d600d6', '#00007b'] },
    sgb_4_b: { id: 'sgb_4_b', name: "4-B", group: 'sgb', colors: ['#f7eff7', '#efa563', '#427b39', '#180808'] },
    sgb_4_c: { id: 'sgb_4_c', name: "4-C", group: 'sgb', colors: ['#ffe7e7', '#dea5d6', '#9ca5e7', '#080000'] },
    sgb_4_d_x: { id: 'sgb_4_d_x', name: "4-D (X)", group: 'sgb', colors: ['#ffffbd', '#94cece', '#4a6b7b', '#08214a'] },
    sgb_4_e: { id: 'sgb_4_e', name: "4-E", group: 'sgb', colors: ['#ffdead', '#e7ad7b', '#7b5a8c', '#002131'] },
    sgb_4_f_f_1_race: { id: 'sgb_4_f_f_1_race', name: "4-F (F-1 Race)", group: 'sgb', colors: ['#bdd6d6', '#de84de', '#8400a5', '#390000'] },
    sgb_4_g_metroid_ii_return_of_samus: { id: 'sgb_4_g_metroid_ii_return_of_samus', name: "4-G (Metroid II Return of Samus)", group: 'sgb', colors: ['#b5e718', '#008463', '#bd215a', '#291000'] },
    sgb_4_h: { id: 'sgb_4_h', name: "4-H", group: 'sgb', colors: ['#ffffce', '#bdc65a', '#848c42', '#425229'] },

    // ── SGB Vaporwave ─────────────────────────────────────────
    sgb2_sgb2ve_1_a_sunset: { id: 'sgb2_sgb2ve_1_a_sunset', name: "SGB2VE 1-A Sunset", group: 'sgb2', colors: ['#f7f794', '#f7a552', '#ef2994', '#1039ad'] },
    sgb2_sgb2ve_1_b_kimochi_wario: { id: 'sgb2_sgb2ve_1_b_kimochi_wario', name: "SGB2VE 1-B Kimochi Wario", group: 'sgb2', colors: ['#f7efbd', '#f7a56b', '#bd63a5', '#4a3973'] },
    sgb2_sgb2ve_1_c_pachinko: { id: 'sgb2_sgb2ve_1_c_pachinko', name: "SGB2VE 1-C Pachinko", group: 'sgb2', colors: ['#f7deef', '#f7947b', '#9c42ef', '#42427b'] },
    sgb2_sgb2ve_1_d_cotton_candy: { id: 'sgb2_sgb2ve_1_d_cotton_candy', name: "SGB2VE 1-D Cotton Candy", group: 'sgb2', colors: ['#f7f7f7', '#84e7ef', '#ffa5ff', '#1039ad'] },
    sgb2_sgb2ve_1_e_absynthe: { id: 'sgb2_sgb2ve_1_e_absynthe', name: "SGB2VE 1-E Absynthe", group: 'sgb2', colors: ['#ffff8c', '#adff5a', '#a5b5ff', '#7b4aad'] },
    sgb2_sgb2ve_1_f_arizona: { id: 'sgb2_sgb2ve_1_f_arizona', name: "SGB2VE 1-F Arizona", group: 'sgb2', colors: ['#defff7', '#ffcece', '#ff4273', '#52529c'] },
    sgb2_sgb2ve_1_g_hot_vibes: { id: 'sgb2_sgb2ve_1_g_hot_vibes', name: "SGB2VE 1-G Hot Vibes", group: 'sgb2', colors: ['#f7ce18', '#f78c18', '#f72973', '#8c18f7'] },
    sgb2_sgb2ve_1_h_sorbet_whip: { id: 'sgb2_sgb2ve_1_h_sorbet_whip', name: "SGB2VE 1-H Sorbet Whip", group: 'sgb2', colors: ['#f7ffc6', '#ffc684', '#ff6b8c', '#63184a'] },
    sgb2_sgb2ve_2_a_bufotoxin: { id: 'sgb2_sgb2ve_2_a_bufotoxin', name: "SGB2VE 2-A Bufotoxin", group: 'sgb2', colors: ['#f7de9c', '#ef8c84', '#009c84', '#104a63'] },
    sgb2_sgb2ve_2_b_dank: { id: 'sgb2_sgb2ve_2_b_dank', name: "SGB2VE 2-B Dank", group: 'sgb2', colors: ['#f7f794', '#63b5bd', '#635284', '#4a1842'] },
    sgb2_sgb2ve_2_c_creampuff: { id: 'sgb2_sgb2ve_2_c_creampuff', name: "SGB2VE 2-C Creampuff", group: 'sgb2', colors: ['#ffdef7', '#f79cad', '#a573f7', '#632963'] },
    sgb2_sgb2ve_2_d_modern_computing: { id: 'sgb2_sgb2ve_2_d_modern_computing', name: "SGB2VE 2-D Modern Computing", group: 'sgb2', colors: ['#f7f7f7', '#6bffbd', '#ff849c', '#101018'] },
    sgb2_sgb2ve_2_e_uranium_glass: { id: 'sgb2_sgb2ve_2_e_uranium_glass', name: "SGB2VE 2-E Uranium Glass", group: 'sgb2', colors: ['#d6ff9c', '#00dede', '#9c42ef', '#4a08ef'] },
    sgb2_sgb2ve_2_f_tenshi: { id: 'sgb2_sgb2ve_2_f_tenshi', name: "SGB2VE 2-F. Tenshi", group: 'sgb2', colors: ['#adf7c6', '#efadce', '#de5ace', '#2142e7'] },
    sgb2_sgb2ve_2_g_87_ninjas: { id: 'sgb2_sgb2ve_2_g_87_ninjas', name: "SGB2VE 2-G 87 Ninjas", group: 'sgb2', colors: ['#c6f7de', '#bdb5f7', '#d63994', '#42427b'] },
    sgb2_sgb2ve_2_h_floral: { id: 'sgb2_sgb2ve_2_h_floral', name: "SGB2VE 2-H Floral", group: 'sgb2', colors: ['#efe7e7', '#ff849c', '#52b59c', '#081018'] },
    sgb2_sgb2ve_3_a_mind_game: { id: 'sgb2_sgb2ve_3_a_mind_game', name: "SGB2VE 3-A Mind Game", group: 'sgb2', colors: ['#f7f7f7', '#f784f7', '#00b5f7', '#4200f7'] },
    sgb2_sgb2ve_3_b_sewer_magic: { id: 'sgb2_sgb2ve_3_b_sewer_magic', name: "SGB2VE 3-B Sewer Magic", group: 'sgb2', colors: ['#f7f794', '#84f7c6', '#8c7be7', '#5a0084'] },
    sgb2_sgb2ve_3_c_galactic_rabbit_trip: { id: 'sgb2_sgb2ve_3_c_galactic_rabbit_trip', name: "SGB2VE 3-C Galactic Rabbit Trip", group: 'sgb2', colors: ['#f7f7ef', '#bdceef', '#52a5ce', '#4a5273'] },
    sgb2_sgb2ve_3_d_frenemy: { id: 'sgb2_sgb2ve_3_d_frenemy', name: "SGB2VE 3-D Frenemy", group: 'sgb2', colors: ['#bdffe7', '#ffd6b5', '#42d6d6', '#1039ad'] },
    sgb2_sgb2ve_3_e_agent_orange: { id: 'sgb2_sgb2ve_3_e_agent_orange', name: "SGB2VE 3-E Agent Orange", group: 'sgb2', colors: ['#ffe742', '#f7a56b', '#e76b84', '#632963'] },
    sgb2_sgb2ve_3_f_backstreet: { id: 'sgb2_sgb2ve_3_f_backstreet', name: "SGB2VE 3-F Backstreet", group: 'sgb2', colors: ['#dedeff', '#ffceb5', '#ff8cbd', '#294a8c'] },
    sgb2_sgb2ve_3_g_eccojam: { id: 'sgb2_sgb2ve_3_g_eccojam', name: "SGB2VE 3-G Eccojam", group: 'sgb2', colors: ['#9cefff', '#ad7be7', '#946cff', '#8c42a5'] },
    sgb2_sgb2ve_3_h_sakura: { id: 'sgb2_sgb2ve_3_h_sakura', name: "SGB2VE 3-H Sakura", group: 'sgb2', colors: ['#f7efb5', '#efb5bd', '#ef73d6', '#4a39b5'] },
    sgb2_sgb2ve_4_a_vector: { id: 'sgb2_sgb2ve_4_a_vector', name: "SGB2VE 4-A Vector", group: 'sgb2', colors: ['#f7d684', '#00b5f7', '#9400f7', '#1039ad'] },
    sgb2_sgb2ve_4_b_slumber: { id: 'sgb2_sgb2ve_4_b_slumber', name: "SGB2VE 4-B Slumber", group: 'sgb2', colors: ['#d6ffff', '#94ceff', '#8c8cf7', '#944ab5'] },
    sgb2_sgb2ve_4_c_lingonberry_butter: { id: 'sgb2_sgb2ve_4_c_lingonberry_butter', name: "SGB2VE 4-C Lingonberry Butter", group: 'sgb2', colors: ['#fff7de', '#ffadce', '#7b84e7', '#21529c'] },
    sgb2_sgb2ve_4_d_zangetsu: { id: 'sgb2_sgb2ve_4_d_zangetsu', name: "SGB2VE 4-D Zangetsu", group: 'sgb2', colors: ['#f7efbd', '#84e7ef', '#31a5c6', '#104a63'] },
    sgb2_sgb2ve_4_e_icy_hot: { id: 'sgb2_sgb2ve_4_e_icy_hot', name: "SGB2VE 4-E Icy Hot", group: 'sgb2', colors: ['#bdfff7', '#d6c6ff', '#ff39ce', '#8c00ff'] },
    sgb2_sgb2ve_4_f_night_driver: { id: 'sgb2_sgb2ve_4_f_night_driver', name: "SGB2VE 4-F Night Driver", group: 'sgb2', colors: ['#ff31ef', '#214aff', '#6b00c6', '#10006b'] },
    sgb2_sgb2ve_4_g_bug_hunt: { id: 'sgb2_sgb2ve_4_g_bug_hunt', name: "SGB2VE 4-G Bug Hunt", group: 'sgb2', colors: ['#f7e7ad', '#f7738c', '#3952bd', '#083963'] },
    sgb2_sgb2ve_4_h_mgb_101: { id: 'sgb2_sgb2ve_4_h_mgb_101', name: "SGB2VE 4-H MGB-101", group: 'sgb2', colors: ['#21ffde', '#00bdc6', '#107ba5', '#004a84'] },

    // ── BGB Emulator ──────────────────────────────────────────
    bgb_bgb_v0_3: { id: 'bgb_bgb_v0_3', name: "BGB_v0.3", group: 'bgb', colors: ['#ecfccc', '#acd494', '#548c74', '#142c3c'] },
    bgb_blue: { id: 'bgb_blue', name: "Blue", group: 'bgb', colors: ['#c0c0ff', '#5f5fff', '#0000c0', '#000060'] },
    bgb_game_boy_kiosk: { id: 'bgb_game_boy_kiosk', name: "Game_Boy_Kiosk", group: 'bgb', colors: ['#ececb4', '#bcbc1c', '#6c6c04', '#143404'] },
    bgb_game_boy_light: { id: 'bgb_game_boy_light', name: "Game_Boy_Light", group: 'bgb', colors: ['#00b581', '#009a71', '#00694a', '#004f3b'] },
    bgb_grey: { id: 'bgb_grey', name: "Grey", group: 'bgb', colors: ['#ececec', '#a4a4a4', '#5c5c5c', '#141414'] },
    bgb_greys_high_contrast: { id: 'bgb_greys_high_contrast', name: "Greys_High_Contrast", group: 'bgb', colors: ['#ffffff', '#b0b0b0', '#686868', '#000000'] },
    bgb_kigb_green_inverted: { id: 'bgb_kigb_green_inverted', name: "KiGB_Green - Inverted", group: 'bgb', colors: ['#50d050', '#40a040', '#307030', '#204020'] },
    bgb_lcd_green_inverted: { id: 'bgb_lcd_green_inverted', name: "LCD_Green - Inverted", group: 'bgb', colors: ['#e4fcd4', '#8cc474', '#346c54', '#0c1c24'] },
    bgb_red_inverted: { id: 'bgb_red_inverted', name: "Red - Inverted", group: 'bgb', colors: ['#ffc0c0', '#ff6060', '#c00000', '#600000'] },
    bgb_yellow_inverted: { id: 'bgb_yellow_inverted', name: "Yellow - Inverted", group: 'bgb', colors: ['#f8f078', '#b0a848', '#686830', '#202010'] },
    bgb_yellow_bgb_inverted: { id: 'bgb_yellow_bgb_inverted', name: "Yellow_BGB- Inverted", group: 'bgb', colors: ['#f4ebbf', '#d2cf4d', '#93a73b', '#556f35'] },
    bgb_no_gmb_brown_inverted: { id: 'bgb_no_gmb_brown_inverted', name: "no$gmb_Brown - Inverted", group: 'bgb', colors: ['#f8e088', '#d8b058', '#987838', '#483818'] },

    // ── SameBoy Emulator ──────────────────────────────────────
    sameboy_desert: { id: 'sameboy_desert', name: "Desert", group: 'sameboy', colors: ['#d2d0b1', '#a49b83', '#746657', '#3e2f30'] },
    sameboy_evening: { id: 'sameboy_evening', name: "Evening", group: 'sameboy', colors: ['#aee4a6', '#539889', '#185569', '#012636'] },
    sameboy_fake_crystal: { id: 'sameboy_fake_crystal', name: "Fake Crystal", group: 'sameboy', colors: ['#9ce7f7', '#4a73bd', '#29317b', '#212931'] },
    sameboy_fog: { id: 'sameboy_fog', name: "Fog", group: 'sameboy', colors: ['#bfd2c3', '#86a39d', '#567273', '#343c37'] },
    sameboy_magic_eggplant: { id: 'sameboy_magic_eggplant', name: "Magic Eggplant", group: 'sameboy', colors: ['#b0e4f1', '#9d69c7', '#842e94', '#36213c'] },
    sameboy_radioactive_pea: { id: 'sameboy_radioactive_pea', name: "Radioactive Pea", group: 'sameboy', colors: ['#b8ce03', '#349e16', '#06731f', '#005221'] },
    sameboy_seaweed: { id: 'sameboy_seaweed', name: "Seaweed", group: 'sameboy', colors: ['#dfe095', '#78a758', '#326542', '#15003f'] },
    sameboy_twilight: { id: 'sameboy_twilight', name: "Twilight", group: 'sameboy', colors: ['#e9d397', '#bd5462', '#861246', '#15003f'] },

    // ── R.A.Helllord ──────────────────────────────────────────
    helllord_classic_blue_le_inverted: { id: 'helllord_classic_blue_le_inverted', name: "Limited Edition Pockets Inverted · Classic Blue LE - inverted", group: 'helllord', colors: ['#5775af', '#1b559e', '#023274', '#000000'] },
    helllord_classic_green_le_inverted: { id: 'helllord_classic_green_le_inverted', name: "Limited Edition Pockets Inverted · Classic Green LE - inverted", group: 'helllord', colors: ['#549d80', '#0b8a68', '#01633f', '#000000'] },
    helllord_classic_indigo_le_inverted: { id: 'helllord_classic_indigo_le_inverted', name: "Limited Edition Pockets Inverted · Classic Indigo LE - inverted", group: 'helllord', colors: ['#7b80b4', '#5457a4', '#263172', '#000000'] },
    helllord_classic_pink_le_inverted: { id: 'helllord_classic_pink_le_inverted', name: "Limited Edition Pockets Inverted · Classic Pink LE - inverted", group: 'helllord', colors: ['#efa1bf', '#eb8cb3', '#d8648b', '#000000'] },
    helllord_classic_red_le_inverted: { id: 'helllord_classic_red_le_inverted', name: "Limited Edition Pockets Inverted · Classic Red LE - inverted", group: 'helllord', colors: ['#cb5d5b', '#bc2b2b', '#95030d', '#000000'] },
    helllord_classic_silver_le_inverted: { id: 'helllord_classic_silver_le_inverted', name: "Limited Edition Pockets Inverted · Classic Silver LE - inverted", group: 'helllord', colors: ['#e0dfde', '#cecece', '#908a85', '#000000'] },
    helllord_classic_spice_orange_le_inverted: { id: 'helllord_classic_spice_orange_le_inverted', name: "Limited Edition Pockets Inverted · Classic Spice Orange LE - inverted", group: 'helllord', colors: ['#e8a36c', '#e38f48', '#c96722', '#000000'] },
    helllord_classic_yellow_le_inverted: { id: 'helllord_classic_yellow_le_inverted', name: "Limited Edition Pockets Inverted · Classic Yellow LE - inverted", group: 'helllord', colors: ['#e8be63', '#d2921d', '#cf8b08', '#000000'] },
    helllord_glow_in_the_dark_le_inverted: { id: 'helllord_glow_in_the_dark_le_inverted', name: "Limited Edition Pockets Inverted · Glow in the Dark LE - inverted", group: 'helllord', colors: ['#8cf68a', '#4dcc80', '#05a56d', '#000000'] },
    helllord_transparent_blue_le_inverted: { id: 'helllord_transparent_blue_le_inverted', name: "Limited Edition Pockets Inverted · Transparent Blue LE - inverted", group: 'helllord', colors: ['#646dcb', '#361aa6', '#1e124f', '#000000'] },
    helllord_transparent_clear_le_inverted: { id: 'helllord_transparent_clear_le_inverted', name: "Limited Edition Pockets Inverted · Transparent Clear LE - inverted", group: 'helllord', colors: ['#9c9a99', '#595959', '#3e3b39', '#000000'] },
    helllord_transparent_green_le_inverted: { id: 'helllord_transparent_green_le_inverted', name: "Limited Edition Pockets Inverted · Transparent Green LE - inverted", group: 'helllord', colors: ['#03ce09', '#00b100', '#003c06', '#000000'] },
    helllord_transparent_orange_le_inverted: { id: 'helllord_transparent_orange_le_inverted', name: "Limited Edition Pockets Inverted · Transparent Orange LE - inverted", group: 'helllord', colors: ['#e56400', '#ad2d01', '#3c1405', '#000000'] },
    helllord_transparent_purple_le_inverted: { id: 'helllord_transparent_purple_le_inverted', name: "Limited Edition Pockets Inverted · Transparent Purple LE - inverted", group: 'helllord', colors: ['#a986bb', '#8d6ea7', '#3c2e49', '#000000'] },
    helllord_transparent_red_le_inverted: { id: 'helllord_transparent_red_le_inverted', name: "Limited Edition Pockets Inverted · Transparent Red LE - inverted", group: 'helllord', colors: ['#c51d21', '#991019', '#6d1a1a', '#000000'] },
    helllord_transparent_smoke_le_inverted: { id: 'helllord_transparent_smoke_le_inverted', name: "Limited Edition Pockets Inverted · Transparent Smoke LE - inverted", group: 'helllord', colors: ['#686464', '#363333', '#282421', '#000000'] },
    helllord_pipboy_amber: { id: 'helllord_pipboy_amber', name: "Pipboy · Pipboy - Amber", group: 'helllord', colors: ['#ffb13b', '#8c6121', '#604317', '#2d1f0b'] },
    helllord_pipboy_blue: { id: 'helllord_pipboy_blue', name: "Pipboy · Pipboy - Blue", group: 'helllord', colors: ['#28ccff', '#16708c', '#0f4b5e', '#07242d'] },
    helllord_pipboy_green: { id: 'helllord_pipboy_green', name: "Pipboy · Pipboy - Green", group: 'helllord', colors: ['#00ee00', '#008e00', '#005f00', '#002f00'] },
    helllord_pipboy_white: { id: 'helllord_pipboy_white', name: "Pipboy · Pipboy - White", group: 'helllord', colors: ['#c1ffff', '#6a8c8c', '#496060', '#202b2b'] },

    // ── Trashuncle ────────────────────────────────────────────
    trashuncle_tu_paisley_park: { id: 'trashuncle_tu_paisley_park', name: "Artistic · TU Paisley Park", group: 'trashuncle', colors: ['#ec89ff', '#d442f0', '#b722d4', '#9200ae'] },
    trashuncle_tu_quicksilver: { id: 'trashuncle_tu_quicksilver', name: "Artistic · TU Quicksilver", group: 'trashuncle', colors: ['#bbbce1', '#a4a5c3', '#717286', '#555555'] },
    trashuncle_tu_blueberry_crush: { id: 'trashuncle_tu_blueberry_crush', name: "Crush · TU Blueberry Crush", group: 'trashuncle', colors: ['#ffffff', '#4dffff', '#2811ff', '#000000'] },
    trashuncle_tu_grape_crush: { id: 'trashuncle_tu_grape_crush', name: "Crush · TU Grape Crush", group: 'trashuncle', colors: ['#ffffff', '#0083eb', '#3d43cb', '#000000'] },
    trashuncle_tu_kiwi_crush: { id: 'trashuncle_tu_kiwi_crush', name: "Crush · TU Kiwi Crush", group: 'trashuncle', colors: ['#ffffff', '#2eef7a', '#059e32', '#000000'] },
    trashuncle_tu_lavender_crush: { id: 'trashuncle_tu_lavender_crush', name: "Crush · TU Lavender Crush", group: 'trashuncle', colors: ['#ffffff', '#ab6a9b', '#812482', '#000000'] },
    trashuncle_tu_orange_crush: { id: 'trashuncle_tu_orange_crush', name: "Crush · TU Orange Crush", group: 'trashuncle', colors: ['#ffffff', '#ff632c', '#c23615', '#000000'] },
    trashuncle_tu_pineapple_crush: { id: 'trashuncle_tu_pineapple_crush', name: "Crush · TU Pineapple Crush", group: 'trashuncle', colors: ['#ffffff', '#ffff80', '#ffff00', '#000000'] },
    trashuncle_tu_strawberry_crush: { id: 'trashuncle_tu_strawberry_crush', name: "Crush · TU Strawberry Crush", group: 'trashuncle', colors: ['#ffffff', '#ff5250', '#ea1211', '#000000'] },
    trashuncle_tu_dmg_bright: { id: 'trashuncle_tu_dmg_bright', name: "DMG · TU DMG Bright", group: 'trashuncle', colors: ['#919707', '#4c7b2b', '#2a6141', '#0c3a1d'] },
    trashuncle_tu_dmg_clean: { id: 'trashuncle_tu_dmg_clean', name: "DMG · TU DMG Clean", group: 'trashuncle', colors: ['#788603', '#496503', '#2b5402', '#174902'] },
    trashuncle_tu_dmg_weak_alt: { id: 'trashuncle_tu_dmg_weak_alt', name: "DMG · TU DMG Weak Alt", group: 'trashuncle', colors: ['#677f31', '#597730', '#54733c', '#2c4d20'] },
    trashuncle_tu_dmg_weak: { id: 'trashuncle_tu_dmg_weak', name: "DMG · TU DMG Weak", group: 'trashuncle', colors: ['#6d833d', '#5e7a40', '#577240', '#364e1a'] },
    trashuncle_tu_gbp_bright: { id: 'trashuncle_tu_gbp_bright', name: "GBP · TU GBP Bright", group: 'trashuncle', colors: ['#ffffff', '#abb8a7', '#879481', '#5b5d5a'] },
    trashuncle_tu_gbp_clean: { id: 'trashuncle_tu_gbp_clean', name: "GBP · TU GBP Clean", group: 'trashuncle', colors: ['#edfff4', '#adbfac', '#98a291', '#3d493b'] },
    trashuncle_tu_gbp_weak_alt: { id: 'trashuncle_tu_gbp_weak_alt', name: "GBP · TU GBP Weak Alt", group: 'trashuncle', colors: ['#848459', '#757952', '#70734e', '#4c4b31'] },
    trashuncle_tu_gbp_weak: { id: 'trashuncle_tu_gbp_weak', name: "GBP · TU GBP Weak", group: 'trashuncle', colors: ['#667159', '#535f49', '#535a42', '#434738'] },
    trashuncle_tu_light_bright: { id: 'trashuncle_tu_light_bright', name: "Light · TU Light Bright", group: 'trashuncle', colors: ['#00e3f3', '#00daea', '#00a1b1', '#006374'] },
    trashuncle_tu_light_clean: { id: 'trashuncle_tu_light_clean', name: "Light · TU Light Clean", group: 'trashuncle', colors: ['#01b4b9', '#00aeaf', '#019fa0', '#007577'] },
    trashuncle_tu_light_dark: { id: 'trashuncle_tu_light_dark', name: "Light · TU Light Dark", group: 'trashuncle', colors: ['#00a5f2', '#0098c5', '#0092d1', '#0076a8'] },
    trashuncle_tu_light_idealized: { id: 'trashuncle_tu_light_idealized', name: "Light · TU Light Idealized", group: 'trashuncle', colors: ['#00ccd5', '#00a6cc', '#0093c5', '#006e9d'] },

    // ── TheWolfBunny64 ────────────────────────────────────────
    wolfbunny_absorbent_and_yellow: { id: 'wolfbunny_absorbent_and_yellow', name: "American Pop Culture Pack · Absorbent and Yellow", group: 'wolfbunny', colors: ['#fff752', '#aec600', '#687600', '#343b00'] },
    wolfbunny_bmo_ver: { id: 'wolfbunny_bmo_ver', name: "American Pop Culture Pack · BMO Ver.", group: 'wolfbunny', colors: ['#c0ffcc', '#99cca3', '#607f66', '#394c3d'] },
    wolfbunny_barbie_pink: { id: 'wolfbunny_barbie_pink', name: "American Pop Culture Pack · Barbie Pink", group: 'wolfbunny', colors: ['#f200a1', '#c10080', '#790050', '#480030'] },
    wolfbunny_bedrock_caveman_vision: { id: 'wolfbunny_bedrock_caveman_vision', name: "American Pop Culture Pack · Bedrock Caveman Vision", group: 'wolfbunny', colors: ['#ff7f00', '#009eb8', '#005e6e', '#002f37'] },
    wolfbunny_bikini_bottom_ver: { id: 'wolfbunny_bikini_bottom_ver', name: "American Pop Culture Pack · Bikini Bottom Ver.", group: 'wolfbunny', colors: ['#f8f880', '#48f8e0', '#2098f0', '#606000'] },
    wolfbunny_blossom_pink: { id: 'wolfbunny_blossom_pink', name: "American Pop Culture Pack · Blossom Pink", group: 'wolfbunny', colors: ['#f59bb2', '#c47c8e', '#7a4d59', '#492e35'] },
    wolfbunny_bubbles_blue: { id: 'wolfbunny_bubbles_blue', name: "American Pop Culture Pack · Bubbles Blue", group: 'wolfbunny', colors: ['#64c4e9', '#509cba', '#326274', '#1e3a45'] },
    wolfbunny_buttercup_green: { id: 'wolfbunny_buttercup_green', name: "American Pop Culture Pack · Buttercup Green", group: 'wolfbunny', colors: ['#bedc8d', '#98b070', '#5f6e46', '#39422a'] },
    wolfbunny_danny_phantom_silver: { id: 'wolfbunny_danny_phantom_silver', name: "American Pop Culture Pack · Danny Phantom Silver", group: 'wolfbunny', colors: ['#abbbcc', '#8895a3', '#555d66', '#33383d'] },
    wolfbunny_fairly_oddpalette: { id: 'wolfbunny_fairly_oddpalette', name: "American Pop Culture Pack · Fairly OddPalette", group: 'wolfbunny', colors: ['#7bb850', '#ce5a99', '#7b365b', '#3d1b2d'] },
    wolfbunny_garfield_vision: { id: 'wolfbunny_garfield_vision', name: "American Pop Culture Pack · Garfield Vision", group: 'wolfbunny', colors: ['#f5ea8b', '#e59436', '#964220', '#2d1309'] },
    wolfbunny_hogwarts_goldius: { id: 'wolfbunny_hogwarts_goldius', name: "American Pop Culture Pack · Hogwarts Goldius", group: 'wolfbunny', colors: ['#b6a571', '#91845a', '#5b5238', '#363121'] },
    wolfbunny_invincible_yellow_and_blue: { id: 'wolfbunny_invincible_yellow_and_blue', name: "American Pop Culture Pack · Invincible Yellow and Blue", group: 'wolfbunny', colors: ['#fee566', '#39c9eb', '#22788d', '#113c46'] },
    wolfbunny_nick_orange: { id: 'wolfbunny_nick_orange', name: "American Pop Culture Pack · Nick Orange", group: 'wolfbunny', colors: ['#ff6700', '#cc5200', '#7f3300', '#4c1e00'] },
    wolfbunny_ninja_turtle_green: { id: 'wolfbunny_ninja_turtle_green', name: "American Pop Culture Pack · Ninja Turtle Green", group: 'wolfbunny', colors: ['#86bc25', '#6b961d', '#435e12', '#28380b'] },
    wolfbunny_optimus_prime_palette: { id: 'wolfbunny_optimus_prime_palette', name: "American Pop Culture Pack · Optimus Prime Palette", group: 'wolfbunny', colors: ['#d3d3d3', '#d92121', '#0047ab', '#001533'] },
    wolfbunny_patrick_star_pink: { id: 'wolfbunny_patrick_star_pink', name: "American Pop Culture Pack · Patrick Star Pink", group: 'wolfbunny', colors: ['#ff808b', '#cc666f', '#7f4045', '#4c2629'] },
    wolfbunny_retro_bogeda: { id: 'wolfbunny_retro_bogeda', name: "American Pop Culture Pack · Retro Bogeda", group: 'wolfbunny', colors: ['#fbfd1b', '#ff6cff', '#6408ff', '#000000'] },
    wolfbunny_rocket_portable_power: { id: 'wolfbunny_rocket_portable_power', name: "American Pop Culture Pack · Rocket Portable Power", group: 'wolfbunny', colors: ['#fee998', '#bdd539', '#213f99', '#09122d'] },
    wolfbunny_rugrats_playtime_palette: { id: 'wolfbunny_rugrats_playtime_palette', name: "American Pop Culture Pack · Rugrats Playtime Palette", group: 'wolfbunny', colors: ['#ffffff', '#ffde17', '#ed1c24', '#662d91'] },
    wolfbunny_sailor_spinach_green: { id: 'wolfbunny_sailor_spinach_green', name: "American Pop Culture Pack · Sailor Spinach Green", group: 'wolfbunny', colors: ['#7bb03c', '#628c30', '#3d581e', '#243412'] },
    wolfbunny_scooby_doo_mystery_ver: { id: 'wolfbunny_scooby_doo_mystery_ver', name: "American Pop Culture Pack · Scooby-Doo Mystery Ver.", group: 'wolfbunny', colors: ['#c6de31', '#f79321', '#8f59a5', '#2a1a31'] },
    wolfbunny_smurfy_blue: { id: 'wolfbunny_smurfy_blue', name: "American Pop Culture Pack · Smurfy Blue", group: 'wolfbunny', colors: ['#2cb9ef', '#2394bf', '#165c77', '#0d3747'] },
    wolfbunny_spongebob_yellow: { id: 'wolfbunny_spongebob_yellow', name: "American Pop Culture Pack · SpongeBob Yellow", group: 'wolfbunny', colors: ['#f7e948', '#c5ba39', '#7b7424', '#4a4515'] },
    wolfbunny_squidward_sea_foam_green: { id: 'wolfbunny_squidward_sea_foam_green', name: "American Pop Culture Pack · Squidward Sea Foam Green", group: 'wolfbunny', colors: ['#b9d7cd', '#94aca4', '#5c6b66', '#37403d'] },
    wolfbunny_swampy_ogre_green: { id: 'wolfbunny_swampy_ogre_green', name: "American Pop Culture Pack · Swampy Ogre Green", group: 'wolfbunny', colors: ['#c1d62e', '#9aab24', '#606b17', '#39400d'] },
    wolfbunny_timmy_turner_pink: { id: 'wolfbunny_timmy_turner_pink', name: "American Pop Culture Pack · Timmy Turner Pink", group: 'wolfbunny', colors: ['#bc486d', '#963957', '#5e2436', '#381520'] },
    wolfbunny_universal_studios_blue: { id: 'wolfbunny_universal_studios_blue', name: "American Pop Culture Pack · Universal Studios Blue", group: 'wolfbunny', colors: ['#036ce2', '#0256b4', '#013671', '#002043'] },
    wolfbunny_animax_blue: { id: 'wolfbunny_animax_blue', name: "Anime and Manga Pack · ANIMAX BLUE", group: 'wolfbunny', colors: ['#3499e8', '#297ab9', '#1a4c74', '#0f2d45'] },
    wolfbunny_all_might_hero_palette: { id: 'wolfbunny_all_might_hero_palette', name: "Anime and Manga Pack · All Might Hero Palette", group: 'wolfbunny', colors: ['#eff0f0', '#f3db43', '#d12021', '#212f79'] },
    wolfbunny_anime_digivice_ver: { id: 'wolfbunny_anime_digivice_ver', name: "Anime and Manga Pack · Anime Digivice Ver.", group: 'wolfbunny', colors: ['#5b7b63', '#48624f', '#2d3d31', '#1b241d'] },
    wolfbunny_anime_expo_red: { id: 'wolfbunny_anime_expo_red', name: "Anime and Manga Pack · Anime Expo Red", group: 'wolfbunny', colors: ['#ee3b33', '#be2f28', '#771d19', '#47110f'] },
    wolfbunny_anime_expo_ver: { id: 'wolfbunny_anime_expo_ver', name: "Anime and Manga Pack · Anime Expo Ver.", group: 'wolfbunny', colors: ['#e5eaeb', '#9ba3a6', '#656e72', '#242a2d'] },
    wolfbunny_berserk_blood: { id: 'wolfbunny_berserk_blood', name: "Anime and Manga Pack · Berserk Blood", group: 'wolfbunny', colors: ['#bb1414', '#951010', '#5d0a0a', '#380606'] },
    wolfbunny_blue_stripes_ver: { id: 'wolfbunny_blue_stripes_ver', name: "Anime and Manga Pack · Blue Stripes Ver.", group: 'wolfbunny', colors: ['#8bd3e1', '#999b9c', '#5b5d5d', '#2d2e2e'] },
    wolfbunny_cardcaptor_pink: { id: 'wolfbunny_cardcaptor_pink', name: "Anime and Manga Pack · Cardcaptor Pink", group: 'wolfbunny', colors: ['#f2f4f7', '#eac3d6', '#e10e82', '#430427'] },
    wolfbunny_colorful_horizons: { id: 'wolfbunny_colorful_horizons', name: "Anime and Manga Pack · Colorful Horizons", group: 'wolfbunny', colors: ['#f6cf72', '#60bdc7', '#d15252', '#373939'] },
    wolfbunny_crunchyroll_orange: { id: 'wolfbunny_crunchyroll_orange', name: "Anime and Manga Pack · Crunchyroll Orange", group: 'wolfbunny', colors: ['#f47522', '#c35d1b', '#7a3a11', '#49230a'] },
    wolfbunny_deku_alpha_emerald: { id: 'wolfbunny_deku_alpha_emerald', name: "Anime and Manga Pack · Deku Alpha Emerald", group: 'wolfbunny', colors: ['#39ad9e', '#2d8a7e', '#1c564f', '#11332f'] },
    wolfbunny_deku_gamma_palette: { id: 'wolfbunny_deku_gamma_palette', name: "Anime and Manga Pack · Deku Gamma Palette", group: 'wolfbunny', colors: ['#f0e8d6', '#b6bec8', '#166668', '#24262b'] },
    wolfbunny_deku_vigilante_palette: { id: 'wolfbunny_deku_vigilante_palette', name: "Anime and Manga Pack · Deku Vigilante Palette", group: 'wolfbunny', colors: ['#ada89a', '#878b92', '#38534e', '#131315'] },
    wolfbunny_demon_slayer_gold: { id: 'wolfbunny_demon_slayer_gold', name: "Anime and Manga Pack · Demon Slayer Gold", group: 'wolfbunny', colors: ['#baaf56', '#948c44', '#5d572b', '#373419'] },
    wolfbunny_doraemon_tricolor: { id: 'wolfbunny_doraemon_tricolor', name: "Anime and Manga Pack · Doraemon Tricolor", group: 'wolfbunny', colors: ['#ffe800', '#00a8f4', '#e60000', '#450000'] },
    wolfbunny_dragon_ball_orange: { id: 'wolfbunny_dragon_ball_orange', name: "Anime and Manga Pack · Dragon Ball Orange", group: 'wolfbunny', colors: ['#f0831d', '#c06817', '#78410e', '#482708'] },
    wolfbunny_dynamight_hero_palette: { id: 'wolfbunny_dynamight_hero_palette', name: "Anime and Manga Pack · Dynamight Hero Palette", group: 'wolfbunny', colors: ['#d1d0cc', '#c84a31', '#29463d', '#161616'] },
    wolfbunny_eva_01: { id: 'wolfbunny_eva_01', name: "Anime and Manga Pack · EVA-01", group: 'wolfbunny', colors: ['#f99b22', '#54cf54', '#765898', '#303345'] },
    wolfbunny_eden_academy_uniform: { id: 'wolfbunny_eden_academy_uniform', name: "Anime and Manga Pack · Eden Academy Uniform", group: 'wolfbunny', colors: ['#f7f8f5', '#dcbc76', '#cc4c47', '#483e39'] },
    wolfbunny_forger_pretense_palette: { id: 'wolfbunny_forger_pretense_palette', name: "Anime and Manga Pack · Forger Pretense Palette", group: 'wolfbunny', colors: ['#8ea99b', '#697d73', '#8d0000', '#000000'] },
    wolfbunny_good_smile_vision: { id: 'wolfbunny_good_smile_vision', name: "Anime and Manga Pack · GOOD SMILE VISION", group: 'wolfbunny', colors: ['#9fa0a0', '#ee7700', '#8e4700', '#472300'] },
    wolfbunny_gear_5_fever: { id: 'wolfbunny_gear_5_fever', name: "Anime and Manga Pack · Gear 5 Fever", group: 'wolfbunny', colors: ['#f7f7f7', '#c5cedf', '#a662cd', '#311d3d'] },
    wolfbunny_goku_gt_gi: { id: 'wolfbunny_goku_gt_gi', name: "Anime and Manga Pack · Goku GT Gi", group: 'wolfbunny', colors: ['#dbe3e6', '#f0ac18', '#3d6ea5', '#122131'] },
    wolfbunny_goku_gi: { id: 'wolfbunny_goku_gi', name: "Anime and Manga Pack · Goku Gi", group: 'wolfbunny', colors: ['#f9f0e1', '#e7612c', '#173f72', '#061222'] },
    wolfbunny_grand_ivory: { id: 'wolfbunny_grand_ivory', name: "Anime and Manga Pack · Grand Ivory", group: 'wolfbunny', colors: ['#d9d6be', '#adab98', '#6c6b5f', '#414039'] },
    wolfbunny_grand_zeno_coat: { id: 'wolfbunny_grand_zeno_coat', name: "Anime and Manga Pack · Grand Zeno Coat", group: 'wolfbunny', colors: ['#fbfbfa', '#fce72d', '#ce26a9', '#3d0b32'] },
    wolfbunny_hokage_orange: { id: 'wolfbunny_hokage_orange', name: "Anime and Manga Pack · Hokage Orange", group: 'wolfbunny', colors: ['#ea8352', '#bb6841', '#754129', '#462718'] },
    wolfbunny_konosuba_sherbet: { id: 'wolfbunny_konosuba_sherbet', name: "Anime and Manga Pack · KonoSuba Sherbet", group: 'wolfbunny', colors: ['#f08200', '#e5006e', '#890042', '#440021'] },
    wolfbunny_kuwabara_blue: { id: 'wolfbunny_kuwabara_blue', name: "Anime and Manga Pack · Kuwabara Blue", group: 'wolfbunny', colors: ['#0088c5', '#006c9d', '#004462', '#00283b'] },
    wolfbunny_legendary_super_saiyan: { id: 'wolfbunny_legendary_super_saiyan', name: "Anime and Manga Pack · Legendary Super Saiyan", group: 'wolfbunny', colors: ['#a6da5b', '#84ae48', '#536d2d', '#31411b'] },
    wolfbunny_lisani_orange: { id: 'wolfbunny_lisani_orange', name: "Anime and Manga Pack · LisAni Orange!", group: 'wolfbunny', colors: ['#eb5e01', '#bc4b00', '#752f00', '#461c00'] },
    wolfbunny_perfect_majin_emperor: { id: 'wolfbunny_perfect_majin_emperor', name: "Anime and Manga Pack · Perfect Majin Emperor", group: 'wolfbunny', colors: ['#fdc1bf', '#a3b453', '#8550a9', '#271832'] },
    wolfbunny_perfected_ultra_instinct: { id: 'wolfbunny_perfected_ultra_instinct', name: "Anime and Manga Pack · Perfected Ultra Instinct", group: 'wolfbunny', colors: ['#c0c8d8', '#99a0ac', '#60646c', '#393c40'] },
    wolfbunny_precure_marble_raspberry: { id: 'wolfbunny_precure_marble_raspberry', name: "Anime and Manga Pack · Precure Marble Raspberry", group: 'wolfbunny', colors: ['#d6225c', '#ab1b49', '#6b112e', '#400a1b'] },
    wolfbunny_pretty_guardian_gold: { id: 'wolfbunny_pretty_guardian_gold', name: "Anime and Manga Pack · Pretty Guardian Gold", group: 'wolfbunny', colors: ['#b4aa82', '#908868', '#5a5541', '#363327'] },
    wolfbunny_saiyan_beast_silver: { id: 'wolfbunny_saiyan_beast_silver', name: "Anime and Manga Pack · Saiyan Beast Silver", group: 'wolfbunny', colors: ['#969baf', '#787c8c', '#4b4d57', '#2d2e34'] },
    wolfbunny_shenron_green: { id: 'wolfbunny_shenron_green', name: "Anime and Manga Pack · Shenron Green", group: 'wolfbunny', colors: ['#5ac34a', '#489c3b', '#2d6125', '#1b3a16'] },
    wolfbunny_straw_hat_red: { id: 'wolfbunny_straw_hat_red', name: "Anime and Manga Pack · Straw Hat Red", group: 'wolfbunny', colors: ['#f8523c', '#c64130', '#7c291e', '#4a1812'] },
    wolfbunny_super_saiyan_3: { id: 'wolfbunny_super_saiyan_3', name: "Anime and Manga Pack · Super Saiyan 3", group: 'wolfbunny', colors: ['#f8c838', '#c6a02c', '#7c641c', '#4a3c10'] },
    wolfbunny_super_saiyan_blue_evolved: { id: 'wolfbunny_super_saiyan_blue_evolved', name: "Anime and Manga Pack · Super Saiyan Blue Evolved", group: 'wolfbunny', colors: ['#1b97d1', '#1578a7', '#0d4b68', '#082d3e'] },
    wolfbunny_super_saiyan_blue: { id: 'wolfbunny_super_saiyan_blue', name: "Anime and Manga Pack · Super Saiyan Blue", group: 'wolfbunny', colors: ['#05bccc', '#0496a3', '#025d66', '#01383d'] },
    wolfbunny_super_saiyan_god: { id: 'wolfbunny_super_saiyan_god', name: "Anime and Manga Pack · Super Saiyan God", group: 'wolfbunny', colors: ['#d70362', '#ac024e', '#6b0131', '#40001d'] },
    wolfbunny_super_saiyan_rose: { id: 'wolfbunny_super_saiyan_rose', name: "Anime and Manga Pack · Super Saiyan Rose", group: 'wolfbunny', colors: ['#f7afb3', '#c58c8f', '#7b5759', '#4a3435'] },
    wolfbunny_super_saiyan: { id: 'wolfbunny_super_saiyan', name: "Anime and Manga Pack · Super Saiyan", group: 'wolfbunny', colors: ['#fefcc1', '#cbc99a', '#7f7e60', '#4c4b39'] },
    wolfbunny_survey_corps_uniform: { id: 'wolfbunny_survey_corps_uniform', name: "Anime and Manga Pack · Survey Corps Uniform", group: 'wolfbunny', colors: ['#acaba9', '#ac7c59', '#593d34', '#321d1a'] },
    wolfbunny_sword_art_cyan: { id: 'wolfbunny_sword_art_cyan', name: "Anime and Manga Pack · Sword Art Cyan", group: 'wolfbunny', colors: ['#59c3e2', '#479cb4', '#2c6171', '#1a3a43'] },
    wolfbunny_team_rocket_uniform: { id: 'wolfbunny_team_rocket_uniform', name: "Anime and Manga Pack · Team Rocket Uniform", group: 'wolfbunny', colors: ['#eeefeb', '#e94e60', '#755e88', '#474f4d'] },
    wolfbunny_tri_digivice_ver: { id: 'wolfbunny_tri_digivice_ver', name: "Anime and Manga Pack · Tri Digivice Ver.", group: 'wolfbunny', colors: ['#848f79', '#697260', '#42473c', '#272a24'] },
    wolfbunny_u_a_high_school_uniform: { id: 'wolfbunny_u_a_high_school_uniform', name: "Anime and Manga Pack · U.A. High School Uniform", group: 'wolfbunny', colors: ['#ededed', '#a4aaaf', '#a02929', '#0c4856'] },
    wolfbunny_uta_vision: { id: 'wolfbunny_uta_vision', name: "Anime and Manga Pack · UTA VISION", group: 'wolfbunny', colors: ['#f4f4f4', '#f1a7b5', '#e24465', '#262c48'] },
    wolfbunny_ultra_instinct_sign: { id: 'wolfbunny_ultra_instinct_sign', name: "Anime and Manga Pack · Ultra Instinct Sign", group: 'wolfbunny', colors: ['#5a686f', '#485358', '#2d3437', '#1b1f21'] },
    wolfbunny_urameshi_green: { id: 'wolfbunny_urameshi_green', name: "Anime and Manga Pack · Urameshi Green", group: 'wolfbunny', colors: ['#4dae88', '#3d8b6c', '#265744', '#173428'] },
    wolfbunny_vegeta_armor: { id: 'wolfbunny_vegeta_armor', name: "Anime and Manga Pack · Vegeta Armor", group: 'wolfbunny', colors: ['#efefef', '#e3c56c', '#1554a9', '#061932'] },
    wolfbunny_animate_vision: { id: 'wolfbunny_animate_vision', name: "Anime and Manga Pack · animate vision", group: 'wolfbunny', colors: ['#ffffff', '#f9be00', '#385eaa', '#231815'] },
    wolfbunny_holoblue: { id: 'wolfbunny_holoblue', name: "Anime and Manga Pack · holoblue", group: 'wolfbunny', colors: ['#b0edfa', '#49c4f2', '#3368d3', '#063f5c'] },
    wolfbunny_1st_vision_pastel: { id: 'wolfbunny_1st_vision_pastel', name: "Bandai Namco Pack · 1st Vision Pastel", group: 'wolfbunny', colors: ['#ea7cb1', '#7faf5a', '#385ead', '#101c33'] },
    wolfbunny_765_production_ver: { id: 'wolfbunny_765_production_ver', name: "Bandai Namco Pack · 765 Production Ver.", group: 'wolfbunny', colors: ['#bbc4e4', '#959cb6', '#5d6272', '#383a44'] },
    wolfbunny_765pro_pink: { id: 'wolfbunny_765pro_pink', name: "Bandai Namco Pack · 765PRO Pink", group: 'wolfbunny', colors: ['#f34f6d', '#c23f57', '#792736', '#481720'] },
    wolfbunny_765pro_tricolor: { id: 'wolfbunny_765pro_tricolor', name: "Bandai Namco Pack · 765PRO TRICOLOR", group: 'wolfbunny', colors: ['#b4e04b', '#e22b30', '#2743d2', '#0b143f'] },
    wolfbunny_a_rise_blue: { id: 'wolfbunny_a_rise_blue', name: "Bandai Namco Pack · A-RISE BLUE", group: 'wolfbunny', colors: ['#30559c', '#26447c', '#182a4e', '#0e192e'] },
    wolfbunny_aqours_blue: { id: 'wolfbunny_aqours_blue', name: "Bandai Namco Pack · Aqours Blue", group: 'wolfbunny', colors: ['#00a0e9', '#0080ba', '#005074', '#003045'] },
    wolfbunny_bandai_namco_tricolor: { id: 'wolfbunny_bandai_namco_tricolor', name: "Bandai Namco Pack · Bandai Namco Tricolor", group: 'wolfbunny', colors: ['#f6b700', '#df4f61', '#0069b1', '#001f35'] },
    wolfbunny_cinderella_blue: { id: 'wolfbunny_cinderella_blue', name: "Bandai Namco Pack · CINDERELLA Blue", group: 'wolfbunny', colors: ['#2681c8', '#1e67a0', '#134064', '#0b263c'] },
    wolfbunny_idol_world_tricolor: { id: 'wolfbunny_idol_world_tricolor', name: "Bandai Namco Pack · IDOL WORLD TRICOLOR!!!", group: 'wolfbunny', colors: ['#ffc30b', '#f34f6d', '#2681c8', '#0b263c'] },
    wolfbunny_liella_purple: { id: 'wolfbunny_liella_purple', name: "Bandai Namco Pack · Liella Purple!", group: 'wolfbunny', colors: ['#a5469b', '#84387c', '#52234d', '#31152e'] },
    wolfbunny_million_live_gold: { id: 'wolfbunny_million_live_gold', name: "Bandai Namco Pack · MILLION LIVE GOLD!", group: 'wolfbunny', colors: ['#cdb261', '#a48e4d', '#665930', '#3d351d'] },
    wolfbunny_million_yellow: { id: 'wolfbunny_million_yellow', name: "Bandai Namco Pack · MILLION Yellow!", group: 'wolfbunny', colors: ['#ffc30b', '#cc9c08', '#7f6105', '#4c3a03'] },
    wolfbunny_moonlight_vision: { id: 'wolfbunny_moonlight_vision', name: "Bandai Namco Pack · Moonlight Vision", group: 'wolfbunny', colors: ['#f8d868', '#3890e8', '#305078', '#101010'] },
    wolfbunny_muse_pink: { id: 'wolfbunny_muse_pink', name: "Bandai Namco Pack · Muse Pink", group: 'wolfbunny', colors: ['#e4007f', '#b60065', '#72003f', '#440026'] },
    wolfbunny_namco_idol_pink: { id: 'wolfbunny_namco_idol_pink', name: "Bandai Namco Pack · Namco Idol Pink", group: 'wolfbunny', colors: ['#ff74b8', '#cc5c93', '#7f3a5c', '#4c2237'] },
    wolfbunny_nijigasaki_orange: { id: 'wolfbunny_nijigasaki_orange', name: "Bandai Namco Pack · Nijigasaki Orange", group: 'wolfbunny', colors: ['#f39800', '#c27900', '#794c00', '#482d00'] },
    wolfbunny_pac_palette: { id: 'wolfbunny_pac_palette', name: "Bandai Namco Pack · PAC-PALETTE", group: 'wolfbunny', colors: ['#ffd800', '#ff8c00', '#dc0000', '#420000'] },
    wolfbunny_pac_man_vision: { id: 'wolfbunny_pac_man_vision', name: "Bandai Namco Pack · Pac-Man Vision", group: 'wolfbunny', colors: ['#ffff00', '#ffb897', '#3732ff', '#000000'] },
    wolfbunny_pac_man_yellow: { id: 'wolfbunny_pac_man_yellow', name: "Bandai Namco Pack · Pac-Man Yellow", group: 'wolfbunny', colors: ['#ffe300', '#ccb500', '#7f7100', '#4c4400'] },
    wolfbunny_radiant_smile_ramp: { id: 'wolfbunny_radiant_smile_ramp', name: "Bandai Namco Pack · RADIANT SMILE RAMP", group: 'wolfbunny', colors: ['#fff89b', '#01b3c4', '#e6016b', '#1b1c81'] },
    wolfbunny_rx_78_2_gundam_mode: { id: 'wolfbunny_rx_78_2_gundam_mode', name: "Bandai Namco Pack · RX-78-2 Gundam Mode", group: 'wolfbunny', colors: ['#dbdcd5', '#dbad40', '#a73736', '#333f3f'] },
    wolfbunny_ryuuguu_sunset: { id: 'wolfbunny_ryuuguu_sunset', name: "Bandai Namco Pack · Ryuuguu Sunset", group: 'wolfbunny', colors: ['#ffe43f', '#fd99e1', '#9238be', '#2b1039'] },
    wolfbunny_shiny_sky_blue: { id: 'wolfbunny_shiny_sky_blue', name: "Bandai Namco Pack · SHINY Sky Blue", group: 'wolfbunny', colors: ['#8dbbff', '#7095cc', '#465d7f', '#2a384c'] },
    wolfbunny_saint_snow_red: { id: 'wolfbunny_saint_snow_red', name: "Bandai Namco Pack · Saint Snow Red", group: 'wolfbunny', colors: ['#bf3936', '#982d2b', '#5f1c1b', '#391110'] },
    wolfbunny_school_idol_blue: { id: 'wolfbunny_school_idol_blue', name: "Bandai Namco Pack · School Idol Blue", group: 'wolfbunny', colors: ['#f9f9f8', '#87adf5', '#3960d7', '#283066'] },
    wolfbunny_school_idol_mix: { id: 'wolfbunny_school_idol_mix', name: "Bandai Namco Pack · School Idol Mix", group: 'wolfbunny', colors: ['#f39800', '#00a0e9', '#a5469b', '#31152e'] },
    wolfbunny_sidem_green: { id: 'wolfbunny_sidem_green', name: "Bandai Namco Pack · SideM Green", group: 'wolfbunny', colors: ['#0fbe94', '#0c9876', '#075f4a', '#04392c'] },
    wolfbunny_sunny_passion_paradise: { id: 'wolfbunny_sunny_passion_paradise', name: "Bandai Namco Pack · Sunny Passion Paradise", group: 'wolfbunny', colors: ['#f0ba40', '#e06846', '#1e6cae', '#092034'] },
    wolfbunny_sylvarant_rose_pink: { id: 'wolfbunny_sylvarant_rose_pink', name: "Bandai Namco Pack · Sylvarant Rose Pink", group: 'wolfbunny', colors: ['#e88486', '#b9696b', '#744243', '#452728'] },
    wolfbunny_tarnished_gold: { id: 'wolfbunny_tarnished_gold', name: "Bandai Namco Pack · Tarnished Gold", group: 'wolfbunny', colors: ['#c19d53', '#9a7d42', '#604e29', '#392f18'] },
    wolfbunny_vulnerable_blue: { id: 'wolfbunny_vulnerable_blue', name: "Bandai Namco Pack · Vulnerable Blue", group: 'wolfbunny', colors: ['#ffb897', '#cc9378', '#7f5c4b', '#3732ff'] },
    wolfbunny_wind_ring_emerald: { id: 'wolfbunny_wind_ring_emerald', name: "Bandai Namco Pack · Wind Ring Emerald", group: 'wolfbunny', colors: ['#28b585', '#20906a', '#145a42', '#0c3627'] },
    wolfbunny_amazon_vision: { id: 'wolfbunny_amazon_vision', name: "Company Pack · Amazon Vision", group: 'wolfbunny', colors: ['#ffffff', '#ff9900', '#008296', '#252f3e'] },
    wolfbunny_android_green: { id: 'wolfbunny_android_green', name: "Company Pack · Android Green", group: 'wolfbunny', colors: ['#3ddc84', '#30b069', '#1e6e42', '#124227'] },
    wolfbunny_apple_silver: { id: 'wolfbunny_apple_silver', name: "Company Pack · Apple Silver", group: 'wolfbunny', colors: ['#a2aaad', '#81888a', '#515556', '#303333'] },
    wolfbunny_duolingo_green: { id: 'wolfbunny_duolingo_green', name: "Company Pack · Duolingo Green", group: 'wolfbunny', colors: ['#58cc02', '#46a301', '#2c6601', '#1a3d00'] },
    wolfbunny_duracell_copper: { id: 'wolfbunny_duracell_copper', name: "Company Pack · Duracell Copper", group: 'wolfbunny', colors: ['#c8895d', '#a06d4a', '#64442e', '#3c291b'] },
    wolfbunny_google_blue: { id: 'wolfbunny_google_blue', name: "Company Pack · Google Blue", group: 'wolfbunny', colors: ['#4285f4', '#346ac3', '#21427a', '#132749'] },
    wolfbunny_google_green: { id: 'wolfbunny_google_green', name: "Company Pack · Google Green", group: 'wolfbunny', colors: ['#34a853', '#298642', '#1a5429', '#0f3218'] },
    wolfbunny_google_red: { id: 'wolfbunny_google_red', name: "Company Pack · Google Red", group: 'wolfbunny', colors: ['#ea4335', '#bb352a', '#75211a', '#46140f'] },
    wolfbunny_google_yellow: { id: 'wolfbunny_google_yellow', name: "Company Pack · Google Yellow", group: 'wolfbunny', colors: ['#fbbc05', '#c89604', '#7d5e02', '#4b3801'] },
    wolfbunny_spotify_green: { id: 'wolfbunny_spotify_green', name: "Company Pack · Spotify Green", group: 'wolfbunny', colors: ['#1ed760', '#18ac4c', '#0f6b30', '#09401c'] },
    wolfbunny_7_eleven_color_combo: { id: 'wolfbunny_7_eleven_color_combo', name: "Food and Drink Pack · 7-Eleven Color Combo", group: 'wolfbunny', colors: ['#ff6c00', '#eb0f2a', '#147350', '#062218'] },
    wolfbunny_baja_blast_beach: { id: 'wolfbunny_baja_blast_beach', name: "Food and Drink Pack · Baja Blast Beach", group: 'wolfbunny', colors: ['#dbe441', '#83ccc5', '#4e7a76', '#273d3b'] },
    wolfbunny_baja_blast_storm: { id: 'wolfbunny_baja_blast_storm', name: "Food and Drink Pack · Baja Blast Storm", group: 'wolfbunny', colors: ['#68c2a4', '#539b83', '#346152', '#1f3a31'] },
    wolfbunny_baskin_robbins_sundae: { id: 'wolfbunny_baskin_robbins_sundae', name: "Food and Drink Pack · Baskin-Robbins Sundae", group: 'wolfbunny', colors: ['#f05097', '#c04078', '#78284b', '#402021'] },
    wolfbunny_burger_king_color_combo: { id: 'wolfbunny_burger_king_color_combo', name: "Food and Drink Pack · Burger King Color Combo", group: 'wolfbunny', colors: ['#f5ebdc', '#ff8732', '#d62300', '#502314'] },
    wolfbunny_cheeto_orange: { id: 'wolfbunny_cheeto_orange', name: "Food and Drink Pack · Cheeto Orange", group: 'wolfbunny', colors: ['#e57600', '#b75e00', '#723b00', '#442300'] },
    wolfbunny_circle_k_color_combo: { id: 'wolfbunny_circle_k_color_combo', name: "Food and Drink Pack · Circle K Color Combo", group: 'wolfbunny', colors: ['#f99b2a', '#ec2e24', '#8d1b15', '#460d0a'] },
    wolfbunny_coca_cola_vision: { id: 'wolfbunny_coca_cola_vision', name: "Food and Drink Pack · Coca-Cola Vision", group: 'wolfbunny', colors: ['#ffffff', '#d7d7d7', '#f40009', '#000000'] },
    wolfbunny_dew_green: { id: 'wolfbunny_dew_green', name: "Food and Drink Pack · Dew Green", group: 'wolfbunny', colors: ['#97d700', '#78ac00', '#4b6b00', '#2d4000'] },
    wolfbunny_domino_s_pizza_vision: { id: 'wolfbunny_domino_s_pizza_vision', name: "Food and Drink Pack · Domino's Pizza Vision", group: 'wolfbunny', colors: ['#ffffff', '#e31837', '#006491', '#000000'] },
    wolfbunny_dr_pepper_red: { id: 'wolfbunny_dr_pepper_red', name: "Food and Drink Pack · Dr Pepper Red", group: 'wolfbunny', colors: ['#8a2231', '#6e1b27', '#451118', '#290a0e'] },
    wolfbunny_dunkin_vision: { id: 'wolfbunny_dunkin_vision', name: "Food and Drink Pack · Dunkin' Vision", group: 'wolfbunny', colors: ['#ff6e0c', '#f20c90', '#910756', '#48032b'] },
    wolfbunny_kentucky_fried_red: { id: 'wolfbunny_kentucky_fried_red', name: "Food and Drink Pack · Kentucky Fried Red", group: 'wolfbunny', colors: ['#ab182f', '#881325', '#550c17', '#33070e'] },
    wolfbunny_krispy_kreme_vision: { id: 'wolfbunny_krispy_kreme_vision', name: "Food and Drink Pack · Krispy Kreme Vision", group: 'wolfbunny', colors: ['#ffffff', '#cf152d', '#166938', '#000000'] },
    wolfbunny_lemon_lime_green: { id: 'wolfbunny_lemon_lime_green', name: "Food and Drink Pack · Lemon-Lime Green", group: 'wolfbunny', colors: ['#f1c545', '#51a631', '#30631d', '#18310e'] },
    wolfbunny_mountain_dew_ver: { id: 'wolfbunny_mountain_dew_ver', name: "Food and Drink Pack · Mountain Dew Ver.", group: 'wolfbunny', colors: ['#ffffff', '#a1d23f', '#d82a34', '#29673c'] },
    wolfbunny_pocari_sweat_blue: { id: 'wolfbunny_pocari_sweat_blue', name: "Food and Drink Pack · POCARI SWEAT BLUE", group: 'wolfbunny', colors: ['#015db2', '#004a8e', '#002e59', '#001b35'] },
    wolfbunny_pepsi_vision: { id: 'wolfbunny_pepsi_vision', name: "Food and Drink Pack · Pepsi Vision", group: 'wolfbunny', colors: ['#ffffff', '#ff1400', '#1414c8', '#000000'] },
    wolfbunny_pizza_hut_red: { id: 'wolfbunny_pizza_hut_red', name: "Food and Drink Pack · Pizza Hut Red", group: 'wolfbunny', colors: ['#e3383e', '#b52c31', '#711c1f', '#441012'] },
    wolfbunny_sprite_green: { id: 'wolfbunny_sprite_green', name: "Food and Drink Pack · Sprite Green", group: 'wolfbunny', colors: ['#009b4e', '#007c3e', '#004d27', '#002e17'] },
    wolfbunny_avgn_raging_volcano: { id: 'wolfbunny_avgn_raging_volcano', name: "Gaming Pack · AVGN Raging Volcano", group: 'wolfbunny', colors: ['#f8b800', '#f83800', '#a81000', '#1c0000'] },
    wolfbunny_blue_bomber_vision: { id: 'wolfbunny_blue_bomber_vision', name: "Gaming Pack · Blue Bomber Vision", group: 'wolfbunny', colors: ['#e2cda7', '#639afc', '#0d4dc4', '#000000'] },
    wolfbunny_bobblun_blue: { id: 'wolfbunny_bobblun_blue', name: "Gaming Pack · Bobblun Blue", group: 'wolfbunny', colors: ['#1fd1fd', '#18a7ca', '#0f687e', '#093e4b'] },
    wolfbunny_bubblun_green: { id: 'wolfbunny_bubblun_green', name: "Gaming Pack · Bubblun Green", group: 'wolfbunny', colors: ['#6adc31', '#54b027', '#356e18', '#1f420e'] },
    wolfbunny_chaos_emerald_green: { id: 'wolfbunny_chaos_emerald_green', name: "Gaming Pack · Chaos Emerald Green", group: 'wolfbunny', colors: ['#a0e000', '#80c800', '#409800', '#208000'] },
    wolfbunny_classic_blurple: { id: 'wolfbunny_classic_blurple', name: "Gaming Pack · Classic Blurple", group: 'wolfbunny', colors: ['#7289da', '#5b6dae', '#38446d', '#222941'] },
    wolfbunny_dmg_pea_green: { id: 'wolfbunny_dmg_pea_green', name: "Gaming Pack · DMG Pea Green", group: 'wolfbunny', colors: ['#d7e894', '#aec440', '#527f39', '#204631'] },
    wolfbunny_ebott_prolouge: { id: 'wolfbunny_ebott_prolouge', name: "Gaming Pack · Ebott Prolouge", group: 'wolfbunny', colors: ['#c08226', '#854a1d', '#4a290b', '#2c1708'] },
    wolfbunny_game_grump_orange: { id: 'wolfbunny_game_grump_orange', name: "Gaming Pack · Game Grump Orange", group: 'wolfbunny', colors: ['#e9762f', '#ba5e25', '#743b17', '#45230e'] },
    wolfbunny_giga_kiwi_dmg: { id: 'wolfbunny_giga_kiwi_dmg', name: "Gaming Pack · Giga Kiwi DMG", group: 'wolfbunny', colors: ['#d0e040', '#a0a830', '#607028', '#384828'] },
    wolfbunny_investigation_yellow: { id: 'wolfbunny_investigation_yellow', name: "Gaming Pack · Investigation Yellow", group: 'wolfbunny', colors: ['#fff919', '#ccc714', '#7f7c0c', '#4c4a07'] },
    wolfbunny_phantom_red: { id: 'wolfbunny_phantom_red', name: "Gaming Pack · Phantom Red", group: 'wolfbunny', colors: ['#fd2639', '#ca1e2d', '#7e131c', '#4b0b11'] },
    wolfbunny_puyo_puyo_green: { id: 'wolfbunny_puyo_puyo_green', name: "Gaming Pack · Puyo Puyo Green", group: 'wolfbunny', colors: ['#48e236', '#39b42b', '#24771b', '#154310'] },
    wolfbunny_s_e_e_s_blue: { id: 'wolfbunny_s_e_e_s_blue', name: "Gaming Pack · S.E.E.S. Blue", group: 'wolfbunny', colors: ['#19d1ff', '#14a7cc', '#0c687f', '#073e4c'] },
    wolfbunny_sega_tokyo_blue: { id: 'wolfbunny_sega_tokyo_blue', name: "Gaming Pack · SEGA Tokyo Blue", group: 'wolfbunny', colors: ['#0082d4', '#0068a9', '#00416a', '#00273f'] },
    wolfbunny_scarlett_green: { id: 'wolfbunny_scarlett_green', name: "Gaming Pack · Scarlett Green", group: 'wolfbunny', colors: ['#9bf00b', '#7cc008', '#4d7805', '#2e4803'] },
    wolfbunny_slime_blue: { id: 'wolfbunny_slime_blue', name: "Gaming Pack · Slime Blue", group: 'wolfbunny', colors: ['#2f8ccc', '#2570a3', '#174666', '#0e2a3d'] },
    wolfbunny_sonic_mega_blue: { id: 'wolfbunny_sonic_mega_blue', name: "Gaming Pack · Sonic Mega Blue", group: 'wolfbunny', colors: ['#4084d9', '#3369ad', '#20426c', '#132741'] },
    wolfbunny_steam_gray: { id: 'wolfbunny_steam_gray', name: "Gaming Pack · Steam Gray", group: 'wolfbunny', colors: ['#c5c3c0', '#9d9c99', '#626160', '#3b3a39'] },
    wolfbunny_teyvat_brown: { id: 'wolfbunny_teyvat_brown', name: "Gaming Pack · Teyvat Brown", group: 'wolfbunny', colors: ['#b89469', '#937654', '#5c4a34', '#372c1f'] },
    wolfbunny_tropical_cyber_space: { id: 'wolfbunny_tropical_cyber_space', name: "Gaming Pack · Tropical Cyber Space", group: 'wolfbunny', colors: ['#63fdfb', '#ef58f7', '#4344c1', '#141439'] },
    wolfbunny_xbox_green: { id: 'wolfbunny_xbox_green', name: "Gaming Pack · Xbox Green", group: 'wolfbunny', colors: ['#92c83e', '#74a031', '#49641f', '#2b3c12'] },
    wolfbunny_christmas_gold: { id: 'wolfbunny_christmas_gold', name: "Holiday Pack · Christmas Gold", group: 'wolfbunny', colors: ['#c0a94b', '#99873c', '#605425', '#393216'] },
    wolfbunny_christmas_silver: { id: 'wolfbunny_christmas_silver', name: "Holiday Pack · Christmas Silver", group: 'wolfbunny', colors: ['#95a8b2', '#77868e', '#4a5459', '#2c3235'] },
    wolfbunny_christmas_ver: { id: 'wolfbunny_christmas_ver', name: "Holiday Pack · Christmas Ver.", group: 'wolfbunny', colors: ['#cbb96a', '#20a465', '#a03232', '#300f0f'] },
    wolfbunny_classy_christmas: { id: 'wolfbunny_classy_christmas', name: "Holiday Pack · Classy Christmas", group: 'wolfbunny', colors: ['#e8e7df', '#8bab95', '#9e5c5e', '#534d57'] },
    wolfbunny_clover_green: { id: 'wolfbunny_clover_green', name: "Holiday Pack · Clover Green", group: 'wolfbunny', colors: ['#39b54a', '#2d903b', '#1c5a25', '#113616'] },
    wolfbunny_cupid_s_love_palette: { id: 'wolfbunny_cupid_s_love_palette', name: "Holiday Pack · Cupid's Love Palette", group: 'wolfbunny', colors: ['#e4cdd3', '#e48397', '#b51a3a', '#5e081e'] },
    wolfbunny_festive_christmas: { id: 'wolfbunny_festive_christmas', name: "Holiday Pack · Festive Christmas", group: 'wolfbunny', colors: ['#bb9b60', '#cc1902', '#224b21', '#0a1609'] },
    wolfbunny_glacial_winter_blue: { id: 'wolfbunny_glacial_winter_blue', name: "Holiday Pack · Glacial Winter Blue", group: 'wolfbunny', colors: ['#87c1e2', '#6c9ab4', '#436071', '#283943'] },
    wolfbunny_grinchy_green: { id: 'wolfbunny_grinchy_green', name: "Holiday Pack · Grinchy Green", group: 'wolfbunny', colors: ['#b7be1c', '#929816', '#5b5f0e', '#363908'] },
    wolfbunny_halloween_ver: { id: 'wolfbunny_halloween_ver', name: "Holiday Pack · Halloween Ver.", group: 'wolfbunny', colors: ['#ffcc00', '#f68c00', '#9540a5', '#2c1331'] },
    wolfbunny_haunted_halloween: { id: 'wolfbunny_haunted_halloween', name: "Holiday Pack · Haunted Halloween", group: 'wolfbunny', colors: ['#caff37', '#ffa52e', '#9e1fff', '#2f094c'] },
    wolfbunny_independence_boy: { id: 'wolfbunny_independence_boy', name: "Holiday Pack · Independence Boy", group: 'wolfbunny', colors: ['#ffffff', '#b31942', '#0a3161', '#000000'] },
    wolfbunny_irish_green: { id: 'wolfbunny_irish_green', name: "Holiday Pack · Irish Green", group: 'wolfbunny', colors: ['#45be76', '#37985e', '#225f3b', '#143923'] },
    wolfbunny_spooky_purple: { id: 'wolfbunny_spooky_purple', name: "Holiday Pack · Spooky Purple", group: 'wolfbunny', colors: ['#9e7cd2', '#7e63a8', '#4f3e69', '#2f253f'] },
    wolfbunny_winter_christmas: { id: 'wolfbunny_winter_christmas', name: "Holiday Pack · Winter Christmas", group: 'wolfbunny', colors: ['#dddddd', '#65b08f', '#ae3b40', '#341113'] },
    wolfbunny_akb48_pink: { id: 'wolfbunny_akb48_pink', name: "J-Pop Pack · AKB48 Pink", group: 'wolfbunny', colors: ['#f676a6', '#c45e84', '#7b3b53', '#492331'] },
    wolfbunny_atarashi_gakko_paretto: { id: 'wolfbunny_atarashi_gakko_paretto', name: "J-Pop Pack · ATARASHI GAKKO PARETTO", group: 'wolfbunny', colors: ['#f4a7eb', '#c375bc', '#7a5375', '#030a5b'] },
    wolfbunny_babymetal_kitsune_red: { id: 'wolfbunny_babymetal_kitsune_red', name: "J-Pop Pack · BABYMETAL KITSUNE RED", group: 'wolfbunny', colors: ['#95000c', '#770009', '#4a0006', '#2c0003'] },
    wolfbunny_hinatazaka46_blue: { id: 'wolfbunny_hinatazaka46_blue', name: "J-Pop Pack · Hinatazaka46 Blue", group: 'wolfbunny', colors: ['#5bbee5', '#4898b7', '#2d5f72', '#1b3944'] },
    wolfbunny_j_pop_idol_sherbet: { id: 'wolfbunny_j_pop_idol_sherbet', name: "J-Pop Pack · J-Pop Idol Sherbet", group: 'wolfbunny', colors: ['#f19db5', '#5bbee5', '#812990', '#260c2b'] },
    wolfbunny_miku_blue: { id: 'wolfbunny_miku_blue', name: "J-Pop Pack · Miku Blue", group: 'wolfbunny', colors: ['#11add5', '#0d8aaa', '#08566a', '#05333f'] },
    wolfbunny_niziu_preplay_palette: { id: 'wolfbunny_niziu_preplay_palette', name: "J-Pop Pack · NiziU PrePlay Palette", group: 'wolfbunny', colors: ['#fff200', '#00b8b0', '#ef3f35', '#47120f'] },
    wolfbunny_nogizaka46_purple: { id: 'wolfbunny_nogizaka46_purple', name: "J-Pop Pack · Nogizaka46 Purple", group: 'wolfbunny', colors: ['#812990', '#672073', '#401448', '#260c2b'] },
    wolfbunny_one_ok_rock_red: { id: 'wolfbunny_one_ok_rock_red', name: "J-Pop Pack · ONE OK ROCK RED", group: 'wolfbunny', colors: ['#b93429', '#942920', '#5c1a14', '#370f0c'] },
    wolfbunny_yoasobi_amaranth: { id: 'wolfbunny_yoasobi_amaranth', name: "J-Pop Pack · YOASOBI AMARANTH", group: 'wolfbunny', colors: ['#f2285a', '#c12048', '#79142d', '#480c1b'] },
    wolfbunny_ana_flight_blue: { id: 'wolfbunny_ana_flight_blue', name: "Japanese Company Pack · ANA Flight Blue", group: 'wolfbunny', colors: ['#00b3f0', '#3b8bc0', '#223f9a', '#00146e'] },
    wolfbunny_familymart_vision: { id: 'wolfbunny_familymart_vision', name: "Japanese Company Pack · FamilyMart Vision", group: 'wolfbunny', colors: ['#008cd6', '#00a040', '#006026', '#003013'] },
    wolfbunny_lawson_blue: { id: 'wolfbunny_lawson_blue', name: "Japanese Company Pack · LAWSON BLUE", group: 'wolfbunny', colors: ['#0068b7', '#005392', '#00345b', '#001f36'] },
    wolfbunny_nhk_silver_gray: { id: 'wolfbunny_nhk_silver_gray', name: "Japanese Company Pack · NHK Silver Gray", group: 'wolfbunny', colors: ['#808080', '#666666', '#404040', '#262626'] },
    wolfbunny_saitama_super_blue: { id: 'wolfbunny_saitama_super_blue', name: "Japanese Company Pack · SAITAMA SUPER BLUE", group: 'wolfbunny', colors: ['#277abc', '#1f6196', '#133d5e', '#0b2438'] },
    wolfbunny_saitama_super_green: { id: 'wolfbunny_saitama_super_green', name: "Japanese Company Pack · SAITAMA SUPER GREEN", group: 'wolfbunny', colors: ['#16ae85', '#118b6a', '#0b5742', '#063427'] },
    wolfbunny_seiko_timely_vision: { id: 'wolfbunny_seiko_timely_vision', name: "Japanese Company Pack · SEIKO Timely Vision", group: 'wolfbunny', colors: ['#ffbf00', '#4393e6', '#0050a5', '#202121'] },
    wolfbunny_shibuya109_pastel: { id: 'wolfbunny_shibuya109_pastel', name: "Japanese Company Pack · SHIBUYA109 PASTEL", group: 'wolfbunny', colors: ['#f2d53f', '#fd87b2', '#3dacb8', '#5503a6'] },
    wolfbunny_sanrio_pink: { id: 'wolfbunny_sanrio_pink', name: "Japanese Company Pack · Sanrio Pink", group: 'wolfbunny', colors: ['#f9c2d0', '#f485a1', '#e74b5a', '#83534d'] },
    wolfbunny_tokyo_skytree_cloudy_blue: { id: 'wolfbunny_tokyo_skytree_cloudy_blue', name: "Japanese Company Pack · TOKYO SKYTREE CLOUDY BLUE", group: 'wolfbunny', colors: ['#82b5c7', '#68909f', '#415a63', '#27363b'] },
    wolfbunny_niconico_sea_green: { id: 'wolfbunny_niconico_sea_green', name: "Japanese Company Pack · niconico sea green", group: 'wolfbunny', colors: ['#19c3a4', '#149c83', '#0c6152', '#073a31'] },
    wolfbunny_bangtan_army_purple: { id: 'wolfbunny_bangtan_army_purple', name: "K-Pop Pack · BANGTAN ARMY PURPLE", group: 'wolfbunny', colors: ['#8048d8', '#6639ac', '#40246c', '#261540'] },
    wolfbunny_blackpink_blink_pink: { id: 'wolfbunny_blackpink_blink_pink', name: "K-Pop Pack · BLACKPINK BLINK PINK", group: 'wolfbunny', colors: ['#f4a7ba', '#c38594', '#7a535d', '#493237'] },
    wolfbunny_exo_eri_cosmic_latte: { id: 'wolfbunny_exo_eri_cosmic_latte', name: "K-Pop Pack · EXO ERI COSMIC LATTE", group: 'wolfbunny', colors: ['#fff8e7', '#ccc6b8', '#7f7c73', '#4c4a45'] },
    wolfbunny_le_sserafim_fearless_blue: { id: 'wolfbunny_le_sserafim_fearless_blue', name: "K-Pop Pack · LE SSERAFIM FEARLESS BLUE", group: 'wolfbunny', colors: ['#81a5f9', '#6784c7', '#40527c', '#26314a'] },
    wolfbunny_nct_ntczen_yellow: { id: 'wolfbunny_nct_ntczen_yellow', name: "K-Pop Pack · NCT NTCZEN YELLOW", group: 'wolfbunny', colors: ['#e2e766', '#b4b851', '#717333', '#43451e'] },
    wolfbunny_seventeen_cool_carat: { id: 'wolfbunny_seventeen_cool_carat', name: "K-Pop Pack · SEVENTEEN COOL CARAT", group: 'wolfbunny', colors: ['#f7cac9', '#92a8d1', '#57647d', '#2b323e'] },
    wolfbunny_shinee_shawol_green: { id: 'wolfbunny_shinee_shawol_green', name: "K-Pop Pack · SHINee SHAWOL GREEN", group: 'wolfbunny', colors: ['#73dbd0', '#5cafa6', '#396d68', '#22413e'] },
    wolfbunny_snsd_so_won_pink: { id: 'wolfbunny_snsd_so_won_pink', name: "K-Pop Pack · SNSD SO-WON PINK", group: 'wolfbunny', colors: ['#f24f7c', '#c13f63', '#79273e', '#481725'] },
    wolfbunny_stray_kids_stay_pink: { id: 'wolfbunny_stray_kids_stay_pink', name: "K-Pop Pack · STRAY KIDS STAY PINK", group: 'wolfbunny', colors: ['#ff4499', '#cc367a', '#7f224c', '#4c142d'] },
    wolfbunny_tropical_twice_apricot: { id: 'wolfbunny_tropical_twice_apricot', name: "K-Pop Pack · TROPICAL TWICE APRICOT", group: 'wolfbunny', colors: ['#fcc89b', '#ff5fa2', '#993961', '#4c1c30'] },
    wolfbunny_3ds_virtual_console_green: { id: 'wolfbunny_3ds_virtual_console_green', name: "Legacy Palette Pack · 3DS Virtual Console Green", group: 'wolfbunny', colors: ['#bdff21', '#9cef29', '#5a8c42', '#4a4a4a'] },
    wolfbunny_3ds_virtual_console_ver: { id: 'wolfbunny_3ds_virtual_console_ver', name: "Legacy Palette Pack · 3DS Virtual Console Ver.", group: 'wolfbunny', colors: ['#cecead', '#a5a58c', '#6b6b52', '#292918'] },
    wolfbunny_bill_s_pc_screen: { id: 'wolfbunny_bill_s_pc_screen', name: "Legacy Palette Pack · Bill's PC Screen", group: 'wolfbunny', colors: ['#f87800', '#b86000', '#783800', '#000000'] },
    wolfbunny_dmg_ver: { id: 'wolfbunny_dmg_ver', name: "Legacy Palette Pack · DMG Ver.", group: 'wolfbunny', colors: ['#7f860f', '#577c44', '#365d48', '#2a453b'] },
    wolfbunny_digivice_ver: { id: 'wolfbunny_digivice_ver', name: "Legacy Palette Pack · Digivice Ver.", group: 'wolfbunny', colors: ['#8c8c73', '#70705c', '#464639', '#2a2a22'] },
    wolfbunny_gamate_ver: { id: 'wolfbunny_gamate_ver', name: "Legacy Palette Pack · Gamate Ver.", group: 'wolfbunny', colors: ['#6ba64a', '#437a63', '#255955', '#12424c'] },
    wolfbunny_game_and_watch_lcd: { id: 'wolfbunny_game_and_watch_lcd', name: "Legacy Palette Pack · Game and Watch LCD", group: 'wolfbunny', colors: ['#c6cbad', '#9ea28a', '#636556', '#3b3c33'] },
    wolfbunny_gameking_ver: { id: 'wolfbunny_gameking_ver', name: "Legacy Palette Pack · GameKing Ver.", group: 'wolfbunny', colors: ['#8cce94', '#6b9c63', '#405d3b', '#184421'] },
    wolfbunny_gamebuino_classic_ver: { id: 'wolfbunny_gamebuino_classic_ver', name: "Legacy Palette Pack · Gamebuino Classic Ver.", group: 'wolfbunny', colors: ['#81a17e', '#678064', '#40503f', '#263025'] },
    wolfbunny_hartung_game_master_ver: { id: 'wolfbunny_hartung_game_master_ver', name: "Legacy Palette Pack · Hartung Game Master Ver.", group: 'wolfbunny', colors: ['#829fa6', '#687f84', '#414f53', '#2d2d2b'] },
    wolfbunny_link_s_awakening_dx_ver: { id: 'wolfbunny_link_s_awakening_dx_ver', name: "Legacy Palette Pack · Link's Awakening DX Ver.", group: 'wolfbunny', colors: ['#f8f8b0', '#78c078', '#688840', '#583820'] },
    wolfbunny_mb_microvision_ver: { id: 'wolfbunny_mb_microvision_ver', name: "Legacy Palette Pack · MB Microvision Ver.", group: 'wolfbunny', colors: ['#a0a0a0', '#808080', '#505050', '#303030'] },
    wolfbunny_mega_man_v_ver: { id: 'wolfbunny_mega_man_v_ver', name: "Legacy Palette Pack · Mega Man V Ver.", group: 'wolfbunny', colors: ['#d0d0d0', '#70a0e0', '#406890', '#082030'] },
    wolfbunny_neo_geo_pocket_ver: { id: 'wolfbunny_neo_geo_pocket_ver', name: "Legacy Palette Pack · Neo Geo Pocket Ver.", group: 'wolfbunny', colors: ['#f0f0f0', '#b0b0b0', '#707070', '#101010'] },
    wolfbunny_nokia_3310_ver: { id: 'wolfbunny_nokia_3310_ver', name: "Legacy Palette Pack · Nokia 3310 Ver.", group: 'wolfbunny', colors: ['#73a684', '#5c8469', '#395342', '#223127'] },
    wolfbunny_pocket_tales_ver: { id: 'wolfbunny_pocket_tales_ver', name: "Legacy Palette Pack · Pocket Tales Ver.", group: 'wolfbunny', colors: ['#d0d860', '#88a000', '#385000', '#000000'] },
    wolfbunny_pocketstation_ver: { id: 'wolfbunny_pocketstation_ver', name: "Legacy Palette Pack · PocketStation Ver.", group: 'wolfbunny', colors: ['#969687', '#78786c', '#4b4b43', '#2d2d28'] },
    wolfbunny_pokemon_pinball_ver: { id: 'wolfbunny_pokemon_pinball_ver', name: "Legacy Palette Pack · Pokemon Pinball Ver.", group: 'wolfbunny', colors: ['#e8f8b8', '#a0b050', '#786030', '#181820'] },
    wolfbunny_pokemon_ver: { id: 'wolfbunny_pokemon_ver', name: "Legacy Palette Pack · Pokemon Ver.", group: 'wolfbunny', colors: ['#f8e8f8', '#f0b088', '#807098', '#181010'] },
    wolfbunny_pokemon_mini_ver: { id: 'wolfbunny_pokemon_mini_ver', name: "Legacy Palette Pack · Pokemon mini Ver.", group: 'wolfbunny', colors: ['#a5b9a5', '#849484', '#525c52', '#1b2d1b'] },
    wolfbunny_poketch_ver: { id: 'wolfbunny_poketch_ver', name: "Legacy Palette Pack · Poketch Ver.", group: 'wolfbunny', colors: ['#70b070', '#508050', '#385030', '#102818'] },
    wolfbunny_rocky_valley_holiday: { id: 'wolfbunny_rocky_valley_holiday', name: "Legacy Palette Pack · Rocky-Valley Holiday", group: 'wolfbunny', colors: ['#c0f0f8', '#d89078', '#805850', '#204008'] },
    wolfbunny_ti_83_ver: { id: 'wolfbunny_ti_83_ver', name: "Legacy Palette Pack · TI-83 Ver.", group: 'wolfbunny', colors: ['#9caa8c', '#7c8870', '#4e5546', '#2e332a'] },
    wolfbunny_tamagotchi_ver: { id: 'wolfbunny_tamagotchi_ver', name: "Legacy Palette Pack · Tamagotchi Ver.", group: 'wolfbunny', colors: ['#f1f0f9', '#c0c0c7', '#78787c', '#3c3838'] },
    wolfbunny_tiger_game_com_ver: { id: 'wolfbunny_tiger_game_com_ver', name: "Legacy Palette Pack · Tiger Game.com Ver.", group: 'wolfbunny', colors: ['#dfff8f', '#6f8f4f', '#0f4f2f', '#000000'] },
    wolfbunny_timing_hero_ver: { id: 'wolfbunny_timing_hero_ver', name: "Legacy Palette Pack · Timing Hero Ver.", group: 'wolfbunny', colors: ['#cccc99', '#8c994c', '#4c6718', '#202e00'] },
    wolfbunny_travel_wood: { id: 'wolfbunny_travel_wood', name: "Legacy Palette Pack · Travel Wood", group: 'wolfbunny', colors: ['#f8d8b0', '#a08058', '#705030', '#482810'] },
    wolfbunny_vmu_ver: { id: 'wolfbunny_vmu_ver', name: "Legacy Palette Pack · VMU Ver.", group: 'wolfbunny', colors: ['#88cca8', '#6ca386', '#446654', '#081480'] },
    wolfbunny_virtual_boy_ver: { id: 'wolfbunny_virtual_boy_ver', name: "Legacy Palette Pack · Virtual Boy Ver.", group: 'wolfbunny', colors: ['#ff0000', '#aa0000', '#550000', '#000000'] },
    wolfbunny_watara_supervision_ver: { id: 'wolfbunny_watara_supervision_ver', name: "Legacy Palette Pack · Watara Supervision Ver.", group: 'wolfbunny', colors: ['#7cc67c', '#54a68c', '#2c6264', '#0c322c'] },
    wolfbunny_wonderswan_ver: { id: 'wolfbunny_wonderswan_ver', name: "Legacy Palette Pack · WonderSwan Ver.", group: 'wolfbunny', colors: ['#fefefe', '#c0c0c0', '#686868', '#2c2c2c'] },
    wolfbunny_camouflage_ver: { id: 'wolfbunny_camouflage_ver', name: "Misc. Palette Pack · Camouflage Ver.", group: 'wolfbunny', colors: ['#bcab90', '#ac7e54', '#79533d', '#373538'] },
    wolfbunny_cherry_blossom_pink: { id: 'wolfbunny_cherry_blossom_pink', name: "Misc. Palette Pack · Cherry Blossom Pink", group: 'wolfbunny', colors: ['#f07eb0', '#c0648c', '#783f58', '#482534'] },
    wolfbunny_emerald_green: { id: 'wolfbunny_emerald_green', name: "Misc. Palette Pack · Emerald Green", group: 'wolfbunny', colors: ['#50c878', '#40a060', '#28643c', '#183c24'] },
    wolfbunny_fool_s_gold_and_silver: { id: 'wolfbunny_fool_s_gold_and_silver', name: "Misc. Palette Pack · Fool's Gold and Silver", group: 'wolfbunny', colors: ['#c5c66d', '#97a1b0', '#5a6069', '#2d3034'] },
    wolfbunny_glitchy_blue: { id: 'wolfbunny_glitchy_blue', name: "Misc. Palette Pack · Glitchy Blue", group: 'wolfbunny', colors: ['#337efb', '#2864c8', '#193f7d', '#0f254b'] },
    wolfbunny_gold_silver_and_bronze: { id: 'wolfbunny_gold_silver_and_bronze', name: "Misc. Palette Pack · Gold, Silver, and Bronze", group: 'wolfbunny', colors: ['#beb049', '#86949a', '#996843', '#2d1f14'] },
    wolfbunny_golden_trophy: { id: 'wolfbunny_golden_trophy', name: "Misc. Palette Pack · Golden Trophy", group: 'wolfbunny', colors: ['#e8d018', '#b9a613', '#74680c', '#453e07'] },
    wolfbunny_greenscale_ver: { id: 'wolfbunny_greenscale_ver', name: "Misc. Palette Pack · Greenscale Ver.", group: 'wolfbunny', colors: ['#9cbe0c', '#6e870a', '#2c6234', '#0c360c'] },
    wolfbunny_leprechaun_green: { id: 'wolfbunny_leprechaun_green', name: "Misc. Palette Pack · Leprechaun Green", group: 'wolfbunny', colors: ['#378861', '#2c6c4d', '#1b4430', '#10281d'] },
    wolfbunny_nightvision_green: { id: 'wolfbunny_nightvision_green', name: "Misc. Palette Pack · Nightvision Green", group: 'wolfbunny', colors: ['#66bf2f', '#519825', '#335f17', '#1e390e'] },
    wolfbunny_rising_sun_red: { id: 'wolfbunny_rising_sun_red', name: "Misc. Palette Pack · Rising Sun Red", group: 'wolfbunny', colors: ['#bc002d', '#960024', '#5d0016', '#38000d'] },
    wolfbunny_treasure_gold: { id: 'wolfbunny_treasure_gold', name: "Misc. Palette Pack · Treasure Gold", group: 'wolfbunny', colors: ['#cbb524', '#a2901c', '#655a12', '#3c360a'] },
    wolfbunny_wild_west_vision: { id: 'wolfbunny_wild_west_vision', name: "Misc. Palette Pack · Wild West Vision", group: 'wolfbunny', colors: ['#d9d7c7', '#c3976a', '#924a36', '#3a160e'] },
    wolfbunny_advanced_indigo: { id: 'wolfbunny_advanced_indigo', name: "Nintendo Pack · Advanced Indigo", group: 'wolfbunny', colors: ['#796aba', '#605494', '#3c355d', '#241f37'] },
    wolfbunny_aegis_cherry: { id: 'wolfbunny_aegis_cherry', name: "Nintendo Pack · Aegis Cherry", group: 'wolfbunny', colors: ['#dd3b64', '#b02f50', '#6e1d32', '#42111e'] },
    wolfbunny_ancient_hisuian_brown: { id: 'wolfbunny_ancient_hisuian_brown', name: "Nintendo Pack · Ancient Hisuian Brown", group: 'wolfbunny', colors: ['#b39f90', '#8f7f73', '#594f48', '#352f2b'] },
    wolfbunny_animal_crossing_green: { id: 'wolfbunny_animal_crossing_green', name: "Nintendo Pack · Animal Crossing Green", group: 'wolfbunny', colors: ['#009b7e', '#007c64', '#004d3f', '#002e25'] },
    wolfbunny_brilliant_diamond_blue: { id: 'wolfbunny_brilliant_diamond_blue', name: "Nintendo Pack · Brilliant Diamond Blue", group: 'wolfbunny', colors: ['#7fbbe1', '#6595b4', '#3f5d70', '#263843'] },
    wolfbunny_collection_of_saga_ver: { id: 'wolfbunny_collection_of_saga_ver', name: "Nintendo Pack · COLLECTION of SaGa Ver.", group: 'wolfbunny', colors: ['#b2c0a8', '#769a67', '#345d51', '#041820'] },
    wolfbunny_champion_s_tunic: { id: 'wolfbunny_champion_s_tunic', name: "Nintendo Pack · Champion's Tunic", group: 'wolfbunny', colors: ['#e2dcb1', '#009edd', '#875b40', '#281b13'] },
    wolfbunny_chozo_blue: { id: 'wolfbunny_chozo_blue', name: "Nintendo Pack · Chozo Blue", group: 'wolfbunny', colors: ['#4eb3e1', '#3e8fb4', '#275970', '#173543'] },
    wolfbunny_dk_arcade_blue: { id: 'wolfbunny_dk_arcade_blue', name: "Nintendo Pack · DK Arcade Blue", group: 'wolfbunny', colors: ['#47a2de', '#3881b1', '#23516f', '#153042'] },
    wolfbunny_dk_barrel_brown: { id: 'wolfbunny_dk_barrel_brown', name: "Nintendo Pack · DK Barrel Brown", group: 'wolfbunny', colors: ['#c3742f', '#9c5c25', '#613a17', '#3a220e'] },
    wolfbunny_dmg_099: { id: 'wolfbunny_dmg_099', name: "Nintendo Pack · DMG-099", group: 'wolfbunny', colors: ['#84b510', '#6bad19', '#3f642f', '#313231'] },
    wolfbunny_dmg_gold: { id: 'wolfbunny_dmg_gold', name: "Nintendo Pack · DMG-GOLD", group: 'wolfbunny', colors: ['#a1b560', '#80904c', '#505a30', '#30361c'] },
    wolfbunny_dmg_switch: { id: 'wolfbunny_dmg_switch', name: "Nintendo Pack · DMG-SWITCH", group: 'wolfbunny', colors: ['#8cad28', '#6c9421', '#426b29', '#214231'] },
    wolfbunny_dream_land_gb_ver: { id: 'wolfbunny_dream_land_gb_ver', name: "Nintendo Pack · Dream Land GB Ver.", group: 'wolfbunny', colors: ['#f6ff70', '#b9d03a', '#788b1d', '#48530e'] },
    wolfbunny_eevee_brown: { id: 'wolfbunny_eevee_brown', name: "Nintendo Pack · Eevee Brown", group: 'wolfbunny', colors: ['#c88d32', '#a07028', '#644619', '#3c2a0f'] },
    wolfbunny_famicom_disk_yellow: { id: 'wolfbunny_famicom_disk_yellow', name: "Nintendo Pack · Famicom Disk Yellow", group: 'wolfbunny', colors: ['#f3c200', '#c29b00', '#796100', '#483a00'] },
    wolfbunny_famicom_frenzy: { id: 'wolfbunny_famicom_frenzy', name: "Nintendo Pack · Famicom Frenzy", group: 'wolfbunny', colors: ['#efecda', '#d9be72', '#a32135', '#231916'] },
    wolfbunny_frog_coin_green: { id: 'wolfbunny_frog_coin_green', name: "Nintendo Pack · Frog Coin Green", group: 'wolfbunny', colors: ['#fff7de', '#00ef00', '#398400', '#003900'] },
    wolfbunny_fury_blue: { id: 'wolfbunny_fury_blue', name: "Nintendo Pack · Fury Blue", group: 'wolfbunny', colors: ['#2b5f98', '#224c79', '#152f4c', '#0c1c2d'] },
    wolfbunny_gamecube_glimmer: { id: 'wolfbunny_gamecube_glimmer', name: "Nintendo Pack · GameCube Glimmer", group: 'wolfbunny', colors: ['#b6bed3', '#11a396', '#cf4151', '#3e1318'] },
    wolfbunny_golden_wild: { id: 'wolfbunny_golden_wild', name: "Nintendo Pack · Golden Wild", group: 'wolfbunny', colors: ['#b99f65', '#947f50', '#5c4f32', '#372f1e'] },
    wolfbunny_goomba_brown: { id: 'wolfbunny_goomba_brown', name: "Nintendo Pack · Goomba Brown", group: 'wolfbunny', colors: ['#aa593b', '#88472f', '#552c1d', '#331a11'] },
    wolfbunny_green_awakening: { id: 'wolfbunny_green_awakening', name: "Nintendo Pack · Green Awakening", group: 'wolfbunny', colors: ['#f1ffdd', '#98db75', '#367058', '#000b16'] },
    wolfbunny_green_banana: { id: 'wolfbunny_green_banana', name: "Nintendo Pack · Green Banana", group: 'wolfbunny', colors: ['#63df08', '#4a9e00', '#396939', '#214900'] },
    wolfbunny_inkling_tricolor: { id: 'wolfbunny_inkling_tricolor', name: "Nintendo Pack · Inkling Tricolor", group: 'wolfbunny', colors: ['#eaff3d', '#ff505e', '#603bff', '#1c114c'] },
    wolfbunny_lcd_clock_green: { id: 'wolfbunny_lcd_clock_green', name: "Nintendo Pack · LCD Clock Green", group: 'wolfbunny', colors: ['#50b580', '#409066', '#285a40', '#183626'] },
    wolfbunny_labo_fawn: { id: 'wolfbunny_labo_fawn', name: "Nintendo Pack · Labo Fawn", group: 'wolfbunny', colors: ['#d7aa73', '#ac885c', '#6b5539', '#403322'] },
    wolfbunny_mario_red: { id: 'wolfbunny_mario_red', name: "Nintendo Pack · Mario Red", group: 'wolfbunny', colors: ['#e10f00', '#b40c00', '#700700', '#430400'] },
    wolfbunny_metallic_paldea_brass: { id: 'wolfbunny_metallic_paldea_brass', name: "Nintendo Pack · Metallic Paldea Brass", group: 'wolfbunny', colors: ['#a29834', '#817929', '#514c1a', '#302d0f'] },
    wolfbunny_neon_blue: { id: 'wolfbunny_neon_blue', name: "Nintendo Pack · Neon Blue", group: 'wolfbunny', colors: ['#0ab9e6', '#0894b8', '#055c73', '#033745'] },
    wolfbunny_neon_green: { id: 'wolfbunny_neon_green', name: "Nintendo Pack · Neon Green", group: 'wolfbunny', colors: ['#1edc00', '#18b000', '#0f6e00', '#094200'] },
    wolfbunny_neon_orange: { id: 'wolfbunny_neon_orange', name: "Nintendo Pack · Neon Orange", group: 'wolfbunny', colors: ['#faa005', '#c88004', '#7d5002', '#4b3001'] },
    wolfbunny_neon_pink: { id: 'wolfbunny_neon_pink', name: "Nintendo Pack · Neon Pink", group: 'wolfbunny', colors: ['#ff3278', '#cc2860', '#7f193c', '#4c0f24'] },
    wolfbunny_neon_purple: { id: 'wolfbunny_neon_purple', name: "Nintendo Pack · Neon Purple", group: 'wolfbunny', colors: ['#b400e6', '#9000b8', '#5a0073', '#360045'] },
    wolfbunny_neon_red: { id: 'wolfbunny_neon_red', name: "Nintendo Pack · Neon Red", group: 'wolfbunny', colors: ['#ff3c28', '#cc3020', '#7f1e14', '#4c120c'] },
    wolfbunny_neon_yellow: { id: 'wolfbunny_neon_yellow', name: "Nintendo Pack · Neon Yellow", group: 'wolfbunny', colors: ['#e6ff00', '#b8cc00', '#737f00', '#454c00'] },
    wolfbunny_odyssey_boy: { id: 'wolfbunny_odyssey_boy', name: "Nintendo Pack · Odyssey Boy", group: 'wolfbunny', colors: ['#acbe8c', '#7e8e67', '#505445', '#222421'] },
    wolfbunny_odyssey_gold: { id: 'wolfbunny_odyssey_gold', name: "Nintendo Pack · Odyssey Gold", group: 'wolfbunny', colors: ['#c2a000', '#9b8000', '#615000', '#3a3000'] },
    wolfbunny_pocket_switch: { id: 'wolfbunny_pocket_switch', name: "Nintendo Pack · POCKET SWITCH", group: 'wolfbunny', colors: ['#b5c69c', '#8d9c7b', '#637251', '#303820'] },
    wolfbunny_pikachu_yellow: { id: 'wolfbunny_pikachu_yellow', name: "Nintendo Pack · Pikachu Yellow", group: 'wolfbunny', colors: ['#ffdc00', '#ccb000', '#7f6e00', '#4c4200'] },
    wolfbunny_pokedex_red: { id: 'wolfbunny_pokedex_red', name: "Nintendo Pack · Pokedex Red", group: 'wolfbunny', colors: ['#ea5450', '#bb4340', '#752a28', '#461918'] },
    wolfbunny_royal_blue: { id: 'wolfbunny_royal_blue', name: "Nintendo Pack · Royal Blue", group: 'wolfbunny', colors: ['#4655f5', '#3844c4', '#232a7a', '#151949'] },
    wolfbunny_shining_pearl_pink: { id: 'wolfbunny_shining_pearl_pink', name: "Nintendo Pack · Shining Pearl Pink", group: 'wolfbunny', colors: ['#d28ea0', '#a87180', '#694750', '#3f2a30'] },
    wolfbunny_sky_pop_ivory: { id: 'wolfbunny_sky_pop_ivory', name: "Nintendo Pack · Sky Pop Ivory", group: 'wolfbunny', colors: ['#e5e0b8', '#bebb95', '#86825c', '#525025'] },
    wolfbunny_super_famicom_supreme: { id: 'wolfbunny_super_famicom_supreme', name: "Nintendo Pack · Super Famicom Supreme", group: 'wolfbunny', colors: ['#feda5a', '#44ac71', '#d94040', '#0846ba'] },
    wolfbunny_super_mushroom_vision: { id: 'wolfbunny_super_mushroom_vision', name: "Nintendo Pack · Super Mushroom Vision", group: 'wolfbunny', colors: ['#f7cec3', '#cc9e22', '#923404', '#000000'] },
    wolfbunny_super_star_pink: { id: 'wolfbunny_super_star_pink', name: "Nintendo Pack · Super Star Pink", group: 'wolfbunny', colors: ['#e52c77', '#b7235f', '#72163b', '#440d23'] },
    wolfbunny_superball_ivory: { id: 'wolfbunny_superball_ivory', name: "Nintendo Pack · Superball Ivory", group: 'wolfbunny', colors: ['#eef0bc', '#bcbc8a', '#828250', '#646432'] },
    wolfbunny_timeless_gold_and_red: { id: 'wolfbunny_timeless_gold_and_red', name: "Nintendo Pack · Timeless Gold and Red", group: 'wolfbunny', colors: ['#c8aa50', '#b91e23', '#6f1215', '#37090a'] },
    wolfbunny_ultra_black: { id: 'wolfbunny_ultra_black', name: "Nintendo Pack · Ultra Black", group: 'wolfbunny', colors: ['#4d5263', '#3d414f', '#262931', '#17181d'] },
    wolfbunny_warioware_microblue: { id: 'wolfbunny_warioware_microblue', name: "Nintendo Pack · WarioWare MicroBlue", group: 'wolfbunny', colors: ['#1189ca', '#0d6da1', '#084465', '#05293c'] },
    wolfbunny_wonder_purple: { id: 'wolfbunny_wonder_purple', name: "Nintendo Pack · Wonder Purple", group: 'wolfbunny', colors: ['#e658df', '#b846b2', '#732c6f', '#451a42'] },
    wolfbunny_yellow_banana: { id: 'wolfbunny_yellow_banana', name: "Nintendo Pack · Yellow Banana", group: 'wolfbunny', colors: ['#ffdf08', '#de9e00', '#ad6939', '#734900'] },
    wolfbunny_yoshi_egg_green: { id: 'wolfbunny_yoshi_egg_green', name: "Nintendo Pack · Yoshi Egg Green", group: 'wolfbunny', colors: ['#66c430', '#519c26', '#336218', '#1e3a0e'] },
    wolfbunny_mlb_vision: { id: 'wolfbunny_mlb_vision', name: "Sports Pack · MLB Vision", group: 'wolfbunny', colors: ['#ffffff', '#057aff', '#bf0d3e', '#041e42'] },
    wolfbunny_nascar_ver: { id: 'wolfbunny_nascar_ver', name: "Sports Pack · NASCAR Ver.", group: 'wolfbunny', colors: ['#ffd659', '#007ac2', '#e4002b', '#000000'] },
    wolfbunny_nba_vision: { id: 'wolfbunny_nba_vision', name: "Sports Pack · NBA Vision", group: 'wolfbunny', colors: ['#ffffff', '#c8102e', '#253b73', '#000000'] },
    wolfbunny_ncaa_blue: { id: 'wolfbunny_ncaa_blue', name: "Sports Pack · NCAA Blue", group: 'wolfbunny', colors: ['#009cde', '#007cb1', '#004e6f', '#002e42'] },
    wolfbunny_nfl_vision: { id: 'wolfbunny_nfl_vision', name: "Sports Pack · NFL Vision", group: 'wolfbunny', colors: ['#ffffff', '#d50a0a', '#013369', '#000000'] },
    wolfbunny_olympic_bronze: { id: 'wolfbunny_olympic_bronze', name: "Sports Pack · Olympic Bronze", group: 'wolfbunny', colors: ['#cd8152', '#a46741', '#664029', '#3d2618'] },
    wolfbunny_olympic_gold: { id: 'wolfbunny_olympic_gold', name: "Sports Pack · Olympic Gold", group: 'wolfbunny', colors: ['#d5b624', '#aa911c', '#6a5b12', '#3f360a'] },
    wolfbunny_olympic_silver: { id: 'wolfbunny_olympic_silver', name: "Sports Pack · Olympic Silver", group: 'wolfbunny', colors: ['#9ea59c', '#7e847c', '#4f524e', '#2f312e'] },
    wolfbunny_pga_tour_vision: { id: 'wolfbunny_pga_tour_vision', name: "Sports Pack · PGA Tour Vision", group: 'wolfbunny', colors: ['#ffffff', '#f1373d', '#003c80', '#000000'] },
    wolfbunny_wwe_white_and_red: { id: 'wolfbunny_wwe_white_and_red', name: "Sports Pack · WWE White and Red", group: 'wolfbunny', colors: ['#ffffff', '#d7182a', '#810e19', '#40070c'] },
    wolfbunny_aquatic_iro: { id: 'wolfbunny_aquatic_iro', name: "Traditional JPN Colors Pack · Aquatic Iro", group: 'wolfbunny', colors: ['#a0d8ef', '#2ca9e1', '#3e62ad', '#192f60'] },
    wolfbunny_fruity_orange: { id: 'wolfbunny_fruity_orange', name: "Traditional JPN Colors Pack · Fruity Orange", group: 'wolfbunny', colors: ['#f3bf88', '#f08300', '#9f563a', '#241a08'] },
    wolfbunny_ghostly_aoi: { id: 'wolfbunny_ghostly_aoi', name: "Traditional JPN Colors Pack · Ghostly Aoi", group: 'wolfbunny', colors: ['#84a2d4', '#5a79ba', '#19448e', '#0f2350'] },
    wolfbunny_golden_kiiro: { id: 'wolfbunny_golden_kiiro', name: "Traditional JPN Colors Pack · Golden Kiiro", group: 'wolfbunny', colors: ['#f8e58c', '#dccb18', '#a69425', '#6a5d21'] },
    wolfbunny_lime_midori: { id: 'wolfbunny_lime_midori', name: "Traditional JPN Colors Pack · Lime Midori", group: 'wolfbunny', colors: ['#e0ebaf', '#aacf53', '#7b8d42', '#475950'] },
    wolfbunny_oni_aka: { id: 'wolfbunny_oni_aka', name: "Traditional JPN Colors Pack · Oni Aka", group: 'wolfbunny', colors: ['#ec6d71', '#d9333f', '#a22041', '#640125'] },
    wolfbunny_sakura_pink: { id: 'wolfbunny_sakura_pink', name: "Traditional JPN Colors Pack · Sakura Pink", group: 'wolfbunny', colors: ['#fdeff2', '#eebbcb', '#e7609e', '#a25768'] },
    wolfbunny_silver_shiro: { id: 'wolfbunny_silver_shiro', name: "Traditional JPN Colors Pack · Silver Shiro", group: 'wolfbunny', colors: ['#dcdddd', '#afafb0', '#727171', '#383c3c'] },
    wolfbunny_tea_midori: { id: 'wolfbunny_tea_midori', name: "Traditional JPN Colors Pack · Tea Midori", group: 'wolfbunny', colors: ['#d6e9ca', '#88cb7f', '#028760', '#333631'] },
    wolfbunny_wisteria_murasaki: { id: 'wolfbunny_wisteria_murasaki', name: "Traditional JPN Colors Pack · Wisteria Murasaki", group: 'wolfbunny', colors: ['#dbd0e6', '#a59aca', '#7058a3', '#2e2930'] },
  };

  Object.assign(window.PALETTES, ext);
}());
